/**
 * Curated trick / skill shots for Shot of the Day.
 * Contact zones use a clock face on the cue ball (player view):
 * 12 = high (follow), 6 = low (draw), 3 = right english, 9 = left english, center = stun.
 */

export type TipZone =
  | 'center'
  | '12-high'
  | '6-low'
  | '3-right'
  | '9-left'
  | '1:30-high-right'
  | '10:30-high-left'
  | '4:30-low-right'
  | '7:30-low-left';

export type StrokeSpeed = 'feather' | 'soft' | 'medium' | 'firm' | 'power';

export type ShotDifficulty = 'Easy' | 'Medium' | 'Hard' | 'Insane';

export type ShotCategory =
  | 'bank'
  | 'combo'
  | 'curve'
  | 'jump'
  | 'masse'
  | 'kick'
  | 'carom'
  | 'novelty'
  | 'position';

export type CatalogShot = {
  id: string;
  name: string;
  tagline: string;
  difficulty: ShotDifficulty;
  category: ShotCategory;
  table: string;
  setup: string[];
  objectBall: string;
  pocket: string;
  tipZone: TipZone;
  tipDetail: string;
  english: string;
  elevation: string;
  speed: StrokeSpeed;
  speedDetail: string;
  bridge: string;
  steps: string[];
  tips: string[];
  commonMistakes: string[];
  successLooksLike: string;
};

export const SHOT_CATALOG: CatalogShot[] = [
  {
    id: 'sotd-01',
    name: 'Rail-First Bank Cross',
    tagline: 'Classic cross-side bank that trains aim geometry',
    difficulty: 'Medium',
    category: 'bank',
    table: '9-foot, object ball mid-rail',
    setup: [
      'Cue ball: center table, one diamond off the foot string.',
      'Object ball (any solid): frozen ~½ ball off the long rail, second diamond from the side pocket.',
      'Target: opposite side pocket.',
    ],
    objectBall: 'Solid of choice (treat as 1-ball)',
    pocket: 'Opposite side pocket via long-rail bank',
    tipZone: 'center',
    tipDetail: 'Hit dead center of the cue ball — pure stun transfer into the bank.',
    english: 'None. Spin ruins bank angle prediction.',
    elevation: 'Level cue. Keep the stick flat.',
    speed: 'medium',
    speedDetail: 'Medium firm — enough to hold the rail line, not so hard it compresses the cushion wrong.',
    bridge: 'Open bridge, stable, chin almost on the stick.',
    steps: [
      'Stand so your aim line is object-ball center → mirror system across the rail.',
      'Use equal-diamond or 1.5× system: contact the rail so rebound aims the side pocket.',
      'Center-ball tip. Pause at the back of the stroke.',
      'Deliver a smooth medium stroke with a 6–8 inch follow-through.',
      'Stay down until the object ball hits the rail.',
    ],
    tips: [
      'If the bank runs long, aim slightly shorter on the rail (closer to the near pocket).',
      'Cloth speed changes bank throw — dial speed first, then micro-aim.',
    ],
    commonMistakes: [
      'Hitting low/high on the CB and changing natural roll into the cushion.',
      'Steering with the tip through contact.',
    ],
    successLooksLike: 'Object ball kisses the long rail cleanly and drops center of the side pocket.',
  },
  {
    id: 'sotd-02',
    name: 'Stop-Shot Ladder',
    tagline: 'Dead-center stun that freezes the cue ball',
    difficulty: 'Easy',
    category: 'position',
    table: 'Center-table straights',
    setup: [
      'Object ball on foot spot.',
      'Cue ball one diamond back, straight in to a corner.',
      'Clear path; no rail first.',
    ],
    objectBall: 'Any',
    pocket: 'Near corner',
    tipZone: 'center',
    tipDetail: 'Exact center of the cue ball for pure stun at impact.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium so the CB arrives sliding, not rolling.',
    bridge: 'Closed bridge optional for control.',
    steps: [
      'Align centers: CB → OB → pocket.',
      'Short backstroke, accelerate smoothly into center.',
      'Stop the tip just past the CB — no scoop.',
      'Watch the CB freeze in place as the OB goes.',
    ],
    tips: ['If CB rolls forward after, you hit too high or too soft from too far.'],
    commonMistakes: ['Elevating the cue and scooping under the ball.'],
    successLooksLike: 'Object ball pockets; cue ball dies within a hand-span of contact point.',
  },
  {
    id: 'sotd-03',
    name: 'Draw Back Two Diamonds',
    tagline: 'Low tip, soft speed, big return',
    difficulty: 'Medium',
    category: 'position',
    table: 'Straight shot to corner',
    setup: [
      'OB on foot spot, corner pocket.',
      'CB one diamond away, slightly off-center line OK but start straight.',
    ],
    objectBall: 'Any',
    pocket: 'Foot corner',
    tipZone: '6-low',
    tipDetail: 'Tip a half-ball below center — low enough for draw, not so low you miscue.',
    english: 'None. Pure backspin.',
    elevation: 'Slight downward (cue almost level; tip just under equator).',
    speed: 'soft',
    speedDetail: 'Soft but crisp. Draw needs spin retention more than raw power.',
    bridge: 'Open or closed; keep wrist quiet.',
    steps: [
      'Chalk thoroughly — draw miscues are tip/chalk failures.',
      'Aim center-to-center for a straight pocket.',
      'Contact CB at 6 o’clock, accelerate through.',
      'Follow through low; don’t lift early.',
      'CB should reverse 1–2 diamonds after contact.',
    ],
    tips: ['Closer CB → more reliable draw. Start short, then lengthen.'],
    commonMistakes: ['Power stroke that skids without reversing.', 'Hitting left/right and curving off line.'],
    successLooksLike: 'OB corners; CB comes straight back at least one full diamond.',
  },
  {
    id: 'sotd-04',
    name: 'Follow Into the Stack',
    tagline: 'High tip rolls you into traffic on purpose',
    difficulty: 'Easy',
    category: 'position',
    table: 'Break-box follow drill (no full rack needed)',
    setup: [
      'Three object balls in a short line near the foot spot.',
      'CB behind the head string, straight at the first ball into a corner.',
    ],
    objectBall: 'Lead ball of the mini-stack',
    pocket: 'Corner',
    tipZone: '12-high',
    tipDetail: 'Tip a half-ball above center for natural roll follow.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — carry roll into the next ball without flying the table.',
    bridge: 'Open bridge.',
    steps: [
      'Pocket the lead ball with high center.',
      'Allow CB to roll forward into the second ball (carom acceptable).',
      'Track where CB finishes — goal is controlled roll, not a blast.',
    ],
    tips: ['If you over-follow, soften speed before lowering the tip.'],
    commonMistakes: ['Hitting too high and miscueing over the top.'],
    successLooksLike: 'Lead ball pockets; CB rolls forward cleanly into the remaining balls.',
  },
  {
    id: 'sotd-05',
    name: 'Inside English Cut',
    tagline: 'Throw the object ball with intentional spin',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Half-ball cut to corner',
    setup: [
      'OB near foot rail, thin-ish cut into corner.',
      'CB two diamonds away at a 30–40° cut angle.',
    ],
    objectBall: 'Any',
    pocket: 'Near corner',
    tipZone: '3-right',
    tipDetail: 'For a right-hand cut (OB going left into pocket), use right (inside) english — tip at 3 o’clock, half tip off center.',
    english: 'Inside — same side as the cut direction through the CB.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium so throw has time to act.',
    bridge: 'Firm closed bridge recommended.',
    steps: [
      'Aim as if without english, then apply inside and slightly adjust aim (collision-induced throw).',
      'Stroke straight — do not steer the tip sideways through the ball.',
      'Watch OB “throw” toward the pocket.',
    ],
    tips: ['Practice both sides. Mirror: left cut → 9 o’clock tip.'],
    commonMistakes: ['Too much tip offset → miscue. Start half-tip only.'],
    successLooksLike: 'Cut that looked slightly under-cut drops from throw; CB drifts with inside spin.',
  },
  {
    id: 'sotd-06',
    name: 'Outside English Hold',
    tagline: 'Kill the natural throw; hold the tangent',
    difficulty: 'Hard',
    category: 'position',
    table: 'Medium cut',
    setup: [
      'Same geometry as inside cut but goal is tight pocket with held CB path.',
      'CB two diamonds out, 30° cut.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: '9-left',
    tipDetail: 'Outside english: tip opposite the cut side (example right-hand cut → left tip at 9).',
    english: 'Outside, half tip.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium to reduce excessive throw while keeping spin.',
    bridge: 'Closed.',
    steps: [
      'Identify natural cut line.',
      'Apply outside english; aim a hair fuller than pure geometry.',
      'Smooth delivery — spin without wrist flick.',
    ],
    tips: ['Outside is for CB path control more than pocketing — pocket first with center, then add spin.'],
    commonMistakes: ['Changing aim wildly; micro-adjust only.'],
    successLooksLike: 'OB pockets; CB takes a tighter, less thrown tangent than center-ball.',
  },
  {
    id: 'sotd-07',
    name: 'Two-Rail Kick to Corner',
    tagline: 'Kick system work for when you’re snookered',
    difficulty: 'Hard',
    category: 'kick',
    table: 'CB near head rail, OB frozen on foot rail',
    setup: [
      'OB frozen center of foot rail.',
      'CB near left head corner area, blocked from direct hit by an imaginary blocker (or real ball).',
      'Path: CB → long rail → short rail → OB into corner.',
    ],
    objectBall: 'Any frozen on foot rail',
    pocket: 'Foot corner after kick contact',
    tipZone: 'center',
    tipDetail: 'Center ball first — learn geometry before adding running english.',
    english: 'None on first reps. Later: running (forward) english to widen.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm so multi-rail path holds, not so hard rails go dead.',
    bridge: 'Long bridge, stable.',
    steps: [
      'Mirror the OB across the first rail to plan contact.',
      'Pick first-rail contact diamond using 2-to-1 or corner-5 systems you know.',
      'Stroke center-ball firm through the first cushion.',
      'Track second rail contact then OB.',
    ],
    tips: ['Mark first-rail aim with a piece of chalk dust for feedback.'],
    commonMistakes: ['Guessing without a system. Pick one system and stick to it for 20 reps.'],
    successLooksLike: 'CB hits two rails then OB; OB moves cleanly toward the corner (pocket is bonus).',
  },
  {
    id: 'sotd-08',
    name: 'Simple Combo: Spot to Corner',
    tagline: 'Line the centers — combos are geometry',
    difficulty: 'Easy',
    category: 'combo',
    table: 'Two-ball combo',
    setup: [
      'Ball A (first) near center.',
      'Ball B on the spot line toward a corner.',
      'CB one diamond behind A, straight through A into B.',
    ],
    objectBall: 'A into B',
    pocket: 'Corner for B',
    tipZone: 'center',
    tipDetail: 'Center stun so you don’t throw the combo line.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium; hard speed throws combos offline.',
    bridge: 'Open.',
    steps: [
      'Line centers of A and B to the pocket — that line is sacred.',
      'Place CB on the extension of that line.',
      'Shoot A full into B with center tip.',
    ],
    tips: ['If B misses left, A hit B too full/thin — adjust contact on B, not random english.'],
    commonMistakes: ['Looking at the pocket instead of the A–B contact.'],
    successLooksLike: 'B drops; A stays near the contact zone.',
  },
  {
    id: 'sotd-09',
    name: 'Carom Off the 9',
    tagline: 'Kiss the money ball into the pocket',
    difficulty: 'Medium',
    category: 'carom',
    table: 'Three-ball carom',
    setup: [
      '9-ball near corner jaw.',
      'Object ball (1) positioned so CB can hit 1 then carom into 9.',
      'CB with a clear shot on 1.',
    ],
    objectBall: '1 then carom to 9',
    pocket: 'Corner for 9',
    tipZone: '12-high',
    tipDetail: 'Slight high center to keep forward roll into the carom.',
    english: 'None initially.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft control — caroms need pace discipline.',
    bridge: 'Open.',
    steps: [
      'Visualize CB path after hitting 1 (tangent + roll).',
      'Hit 1 so the CB’s post-collision path intersects the 9 into the pocket.',
      'High-center soft stroke.',
    ],
    tips: ['Ghost-ball aiming on 1 while planning CB exit angle.'],
    commonMistakes: ['Pocketing 1 but missing the carom line — film from above if you can.'],
    successLooksLike: '1 moves aside; CB kisses 9 into the corner.',
  },
  {
    id: 'sotd-10',
    name: 'Rail Cut Thin as Hair',
    tagline: 'Frozen rail thin cut — soft touch masterclass',
    difficulty: 'Hard',
    category: 'position',
    table: 'OB frozen on long rail',
    setup: [
      'OB frozen mid long rail.',
      'CB in the kitchen or mid-table cutting OB thin into the corner.',
    ],
    objectBall: 'Frozen rail ball',
    pocket: 'Downstream corner',
    tipZone: 'center',
    tipDetail: 'Center tip; thin cut needs clean hit.',
    english: 'None or a whisper of outside later.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather–soft. Hard thin cuts rattle jaws.',
    bridge: 'Long, stable, low.',
    steps: [
      'See a sliver of the OB — aim to shave ⅛–¼ ball.',
      'Soft center-ball stroke.',
      'Trust the rail help if contact is slightly thick.',
    ],
    tips: ['If it rattles long, you were too thick or too hard.'],
    commonMistakes: ['Power stroke on a touch shot.'],
    successLooksLike: 'OB creeps along the rail and falls without a rattle.',
  },
  {
    id: 'sotd-11',
    name: 'Force Follow Over Distance',
    tagline: 'High tip + firm stroke = table-length follow',
    difficulty: 'Medium',
    category: 'position',
    table: 'Long straight',
    setup: [
      'OB near foot corner pocket area.',
      'CB near head string, straight-ish in.',
    ],
    objectBall: 'Any',
    pocket: 'Foot corner',
    tipZone: '12-high',
    tipDetail: 'High center, almost maximum without miscue.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm — you need roll to survive distance.',
    bridge: 'Open, elevated hand for comfort on high tip.',
    steps: [
      'Chalk well for high contact.',
      'Smooth acceleration; full follow-through high.',
      'CB should travel well past the OB after the pot.',
    ],
    tips: ['If you miscue, lower the tip half a tip and keep firm speed.'],
    commonMistakes: ['Jabbing; high tip needs a pure stroke.'],
    successLooksLike: 'OB pockets; CB continues forward 2+ diamonds past contact.',
  },
  {
    id: 'sotd-12',
    name: 'Power Draw Escape',
    tagline: 'Low tip, firm stroke, drag the CB home',
    difficulty: 'Hard',
    category: 'position',
    table: 'Long draw',
    setup: [
      'OB near foot, corner pocket.',
      'CB 2–2.5 diamonds away, straight.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: '6-low',
    tipDetail: 'Low as you dare with good chalk — full tip below center.',
    english: 'None.',
    elevation: 'Slight down angle.',
    speed: 'firm',
    speedDetail: 'Firm and crisp — not wild. Spin + speed both matter.',
    bridge: 'Closed bridge preferred.',
    steps: [
      'Chalk, breathe, low tip alignment check.',
      'Accelerate through the CB; long low follow-through.',
      'CB should rocket back toward the head of the table.',
    ],
    tips: ['Warm up with soft draw first — power draw is a finisher.'],
    commonMistakes: ['Scooping under the ball (foul territory / jump).'],
    successLooksLike: 'OB pockets; CB returns past the center string.',
  },
  {
    id: 'sotd-13',
    name: 'Bank the 9 Off Two Rails',
    tagline: 'Show-off bank for highlight reels',
    difficulty: 'Insane',
    category: 'bank',
    table: '9 near center, bank long→short→corner',
    setup: [
      '9-ball slightly off center.',
      'CB with a clear shot to drive 9 into the long rail first.',
    ],
    objectBall: '9-ball',
    pocket: 'Far corner after two cushions',
    tipZone: 'center',
    tipDetail: 'Center ball for predictable bank angles.',
    english: 'None until consistent; then slight running english.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail pace.',
    bridge: 'Solid closed.',
    steps: [
      'Plan rail1 and rail2 contacts with diamond system.',
      'Hit 9 full enough to take speed into rail1.',
      'Stay down — this shot rewards patience more than muscle.',
    ],
    tips: ['Call it only when you’ve made 3/10 in practice.'],
    commonMistakes: ['Too thin on 9 — dies on first rail.'],
    successLooksLike: '9 takes two rails and disappears into the corner. Crowd optional.',
  },
  {
    id: 'sotd-14',
    name: 'Curve Around a Blocker',
    tagline: 'Massé-lite swerve for soft obstacles',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Blocker ball mid-path',
    setup: [
      'OB straight to corner but a blocker sits slightly offline on the natural path.',
      'CB needs a gentle curve (not full massé) to pass the blocker.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: '1:30-high-right',
    tipDetail: 'High-right (or high-left) with elevated cue ~20–30° for swerve.',
    english: 'Side + a bit of roll.',
    elevation: 'Cue elevated 20–30 degrees — not vertical.',
    speed: 'soft',
    speedDetail: 'Soft so curve has time before contact.',
    bridge: 'Short elevated bridge; careful balance.',
    steps: [
      'Elevate cue modestly.',
      'Hit high-side quadrant; stroke down the elevated line.',
      'CB should arc around the blocker then straighten into OB.',
    ],
    tips: ['This is swerve, not circus massé. Small elevation first.'],
    commonMistakes: ['90° elevation and jumping the table.'],
    successLooksLike: 'CB bends past the blocker and still pockets the OB.',
  },
  {
    id: 'sotd-15',
    name: 'Jump Over the Troublemaker',
    tagline: 'Controlled jump shot — legal elevation',
    difficulty: 'Hard',
    category: 'jump',
    table: 'Short jump over a blocker',
    setup: [
      'Blocker on the line between CB and OB.',
      'OB close beyond the blocker; short jump only.',
      'Use a jump cue if you have one; otherwise very elevated playing cue carefully.',
    ],
    objectBall: 'Any close beyond blocker',
    pocket: 'Any nearby',
    tipZone: 'center',
    tipDetail: 'Center of CB, elevated stick 45°+.',
    english: 'None.',
    elevation: '45–60 degrees.',
    speed: 'firm',
    speedDetail: 'Short firm dart stroke — not a swing from the shoulder.',
    bridge: 'Dart grip / short bridge above the ball.',
    steps: [
      'Chalk, elevate, aim center.',
      'Dart the tip into the top of the CB with a quick punch.',
      'CB jumps the blocker and lands before the OB.',
    ],
    tips: ['Practice jump height on empty table first — protect cloth.'],
    commonMistakes: ['Scoop foul (hitting below center with elevation). Always hit down into the ball.'],
    successLooksLike: 'CB clears the blocker cleanly and contacts OB after landing.',
  },
  {
    id: 'sotd-16',
    name: 'Massé Orbit (Training Version)',
    tagline: 'Steep elevation curve for advanced players only',
    difficulty: 'Insane',
    category: 'masse',
    table: 'CB near rail, OB nearby around obstacle',
    setup: [
      'OB one diamond away, angle blocked.',
      'CB with room to elevate safely (not near light fixtures).',
    ],
    objectBall: 'Nearby OB',
    pocket: 'Optional — prioritize CB curve path first',
    tipZone: '4:30-low-right',
    tipDetail: 'Low-side hit with steep cue — extreme friction spin.',
    english: 'Heavy side + draw component.',
    elevation: '60–80 degrees. Cloth risk: use old cloth / careful practice.',
    speed: 'soft',
    speedDetail: 'Soft punch — massé is spin, not power.',
    bridge: 'Mechanical or very stable elevated bridge.',
    steps: [
      'Only attempt if your room allows elevated cues safely.',
      'Steep cue, low-side tip, short stroke.',
      'Watch CB path curve dramatically.',
    ],
    tips: ['Film from above. Celebrate path, not just pocket.'],
    commonMistakes: ['Ripping the cloth — if unsure, skip and do swerve (sotd-14) instead.'],
    successLooksLike: 'CB takes a banana path around the obstacle toward the OB.',
  },
  {
    id: 'sotd-17',
    name: 'Rail-First Kick Safety',
    tagline: 'Not a pot — a pro safety that wins frames',
    difficulty: 'Medium',
    category: 'kick',
    table: 'Snookered on the 8',
    setup: [
      'Opponent’s ball blocking direct path to your OB.',
      'Kick one rail to thin-touch your OB and hide CB.',
    ],
    objectBall: 'Your ball (thin touch)',
    pocket: 'None — legal contact + safe leave',
    tipZone: 'center',
    tipDetail: 'Center for predictable first rail.',
    english: 'None or slight running later.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft so the thin touch doesn’t sell out.',
    bridge: 'Long.',
    steps: [
      'Pick a rail contact that guarantees a hit on your OB.',
      'Prefer thin contact and CB death behind a cluster.',
      'Execute soft center-ball kick.',
    ],
    tips: ['In race formats, this shot wins more matches than trick pots.'],
    commonMistakes: ['Blasting into a double-kiss sellout.'],
    successLooksLike: 'Legal hit; opponent is left tough or hooked.',
  },
  {
    id: 'sotd-18',
    name: 'Frozen Combo Rail Run',
    tagline: 'Two balls frozen on the rail — precision cut',
    difficulty: 'Hard',
    category: 'combo',
    table: 'Long rail freeze pair',
    setup: [
      'Ball B frozen on rail near corner.',
      'Ball A frozen to B, slightly offline.',
      'CB with a ¾ hit available on A.',
    ],
    objectBall: 'A → B',
    pocket: 'Corner for B',
    tipZone: 'center',
    tipDetail: 'Center; frozen combos hate spin.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium.',
    bridge: 'Stable.',
    steps: [
      'Line the contact through A into B along the rail line.',
      'Hit A so it transfers cleanly; avoid heavy throw.',
    ],
    tips: ['If B freezes and dies, you need a fuller hit on A.'],
    commonMistakes: ['English for no reason.'],
    successLooksLike: 'B slides on the rail into the corner.',
  },
  {
    id: 'sotd-19',
    name: 'Wing Shot Bank',
    tagline: 'Flying cut-bank hybrid for shape',
    difficulty: 'Hard',
    category: 'bank',
    table: 'OB near side, bank to corner',
    setup: [
      'OB a diamond off the side rail.',
      'CB creating a cut-bank into the opposite corner.',
    ],
    objectBall: 'Any',
    pocket: 'Opposite corner via rail',
    tipZone: 'center',
    tipDetail: 'Center first; add running english only after makes.',
    english: 'Optional slight running (tip toward direction of travel along rail).',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium firm.',
    bridge: 'Open.',
    steps: [
      'See cut angle into the rail, then bank angle out.',
      'Commit to a single contact point on the cushion.',
      'Smooth stroke; stay down.',
    ],
    tips: ['Call the rail contact out loud — forces specificity.'],
    commonMistakes: ['Mixing cut and bank guesses mid-stroke.'],
    successLooksLike: 'OB hits the intended diamond and tracks to the corner.',
  },
  {
    id: 'sotd-20',
    name: 'Length of the Table Stop',
    tagline: 'Stun from distance — timing the slide',
    difficulty: 'Hard',
    category: 'position',
    table: 'CB head string to foot spot',
    setup: [
      'OB foot spot into corner.',
      'CB just past head string, straight.',
    ],
    objectBall: 'Any',
    pocket: 'Foot corner',
    tipZone: 'center',
    tipDetail: 'Center; speed creates slide that dies into stun at impact.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — calibrated so CB is still sliding at contact.',
    bridge: 'Long open.',
    steps: [
      'Center aim, medium stroke.',
      'If CB rolls forward after, hit firmer or lower slightly.',
      'If CB draws, you hit too low.',
    ],
    tips: ['Distance stun is a feel skill — log speeds that work on your cloth.'],
    commonMistakes: ['Copying bar-table speed on a fast 9-footer.'],
    successLooksLike: 'Long pot; CB barely drifts after contact.',
  },
  {
    id: 'sotd-21',
    name: 'Reverse English Bank',
    tagline: 'Kill the rail rebound for a short bank',
    difficulty: 'Insane',
    category: 'bank',
    table: 'Short cross-bank',
    setup: [
      'OB near side rail banking short into the near corner.',
      'CB with a fairly straight hit into the OB.',
    ],
    objectBall: 'Any',
    pocket: 'Near corner via short bank',
    tipZone: '9-left',
    tipDetail: 'Use reverse (check) english relative to bank direction to shorten rebound.',
    english: 'Reverse / check english.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium; reverse bites better without blasting.',
    bridge: 'Closed.',
    steps: [
      'Identify natural bank (too long).',
      'Apply reverse english and aim for a shorter rail path.',
      'Soft delivery so spin lives until the rail.',
    ],
    tips: ['Master center banks before reverse banks.'],
    commonMistakes: ['Overspin miscue on the side of the CB.'],
    successLooksLike: 'Bank that would run long dies short into the corner.',
  },
  {
    id: 'sotd-22',
    name: 'Ticket Pocket Thin Kick',
    tagline: 'Kick thin for shape into a side',
    difficulty: 'Hard',
    category: 'kick',
    table: 'OB near side pocket jaw',
    setup: [
      'OB almost pocketed in the side, slightly frozen off jaw.',
      'CB needing a one-rail kick to nick it in.',
    ],
    objectBall: 'Near side-pocket hangar',
    pocket: 'Side',
    tipZone: 'center',
    tipDetail: 'Center first.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — hangers die if overhit after kick.',
    bridge: 'Long.',
    steps: [
      'Plan rail contact that creates a thin nick on the hangar.',
      'Soft kick; don’t double-kiss.',
    ],
    tips: ['If the hangar is truly frozen in the jaw, a firm direct tap may be better — read the freeze.'],
    commonMistakes: ['Hero blast that rattles the side.'],
    successLooksLike: 'Gentle kick-nick; ball drops side center.',
  },
  {
    id: 'sotd-23',
    name: 'Stack Split with Soft Stun',
    tagline: 'Open a cluster without moving the world',
    difficulty: 'Medium',
    category: 'position',
    table: 'Three-ball cluster mid-table',
    setup: [
      'Three balls lightly clustered.',
      'CB with a stun shot into the key ball that splits the pack.',
    ],
    objectBall: 'Key ball of cluster',
    pocket: 'Optional; priority is controlled split',
    tipZone: 'center',
    tipDetail: 'Stun center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft stun — energy transfers without explosion.',
    bridge: 'Open.',
    steps: [
      'Identify the key ball whose contact opens lanes.',
      'Soft center hit; watch the pack open.',
    ],
    tips: ['In real matches, sometimes leave the cluster and play safe instead.'],
    commonMistakes: ['Power splits that sell out both balls to opponent.'],
    successLooksLike: 'Cluster opens with balls still near the middle — controllable.',
  },
  {
    id: 'sotd-24',
    name: 'Behind-the-Back Novelty (Rail Assist)',
    tagline: 'Party trick: one-handed rail bridge — control first',
    difficulty: 'Medium',
    category: 'novelty',
    table: 'Easy straight pot',
    setup: [
      'Dead straight 6-inch pot.',
      'Bridge hand only as a rail rest; stroke with care (no true behind-back needed if unsafe).',
      'Optional: off-hand stroke for novelty once potting is reliable.',
    ],
    objectBall: 'Any short pot',
    pocket: 'Near corner',
    tipZone: 'center',
    tipDetail: 'Center — novelty is hard enough.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft.',
    bridge: 'Rail bridge or mechanical.',
    steps: [
      'Do not risk injury or table lights.',
      'Use rail bridge; soft center stroke.',
      'Only add flair after 8/10 make rate.',
    ],
    tips: ['Film it. RackUp highlight reel fuel.'],
    commonMistakes: ['Trying full behind-the-back before you can pot one-handed from the rail.'],
    successLooksLike: 'Ball drops; you look ridiculous in the best way.',
  },
  {
    id: 'sotd-25',
    name: 'Double Kiss Escape',
    tagline: 'Use the kiss on purpose when frozen',
    difficulty: 'Hard',
    category: 'carom',
    table: 'CB nearly frozen to OB on rail',
    setup: [
      'CB almost touching OB on the long rail.',
      'Natural full hit would double-kiss and stick.',
      'Plan a controlled double-kiss leave or thin free the OB.',
    ],
    objectBall: 'Rail pair',
    pocket: 'If available; else safe free',
    tipZone: '1:30-high-right',
    tipDetail: 'Slight high-side to alter kiss geometry.',
    english: 'Small side.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft experiment — map results.',
    bridge: 'Short.',
    steps: [
      'Hit thin enough to free one ball, or accept intentional kiss.',
      'Log which tip zones free the ball on your cloth.',
    ],
    tips: ['Frozen balls are physics puzzles — patience > ego.'],
    commonMistakes: ['Blasting frozen balls and scratching.'],
    successLooksLike: 'You free a ball without a disaster scratch.',
  },
  {
    id: 'sotd-26',
    name: 'Side-Pocket Soft Cut',
    tagline: 'The underrated money cut',
    difficulty: 'Medium',
    category: 'position',
    table: 'OB mid-table into side',
    setup: [
      'OB one diamond above the side pocket.',
      'CB below, creating a 30–45° cut into the side.',
    ],
    objectBall: 'Any',
    pocket: 'Side',
    tipZone: 'center',
    tipDetail: 'Center tip; side pockets punish spin.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — sides rattle when overhit.',
    bridge: 'Open.',
    steps: [
      'Ghost ball aim for the side mouth center, not the back of the pocket.',
      'Soft center stroke; stay down.',
    ],
    tips: ['Aim slightly deeper into the pocket on fast cloth.'],
    commonMistakes: ['Power cutting sides — highest rattle rate in pool.',
    ],
    successLooksLike: 'Clean center side pocket, no rail rattle.',
  },
  {
    id: 'sotd-27',
    name: 'Lengthwise Bank Cross-Corner',
    tagline: 'Big table bank for diamond students',
    difficulty: 'Hard',
    category: 'bank',
    table: 'OB center, bank long into corner',
    setup: [
      'OB near center diamond.',
      'CB with a full-ish hit available to send OB into a long rail then corner.',
    ],
    objectBall: 'Any',
    pocket: 'Corner after long-rail bank',
    tipZone: 'center',
    tipDetail: 'Center ball.',
    english: 'None first.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm bank speed.',
    bridge: 'Closed.',
    steps: [
      'Use corner-5 or equal-distance system for long banks.',
      'Commit to rail contact; stroke firm center.',
    ],
    tips: ['Banks are 50% speed discipline — pick one speed for a practice block.'],
    commonMistakes: ['Changing speed every attempt with the same aim.'],
    successLooksLike: 'OB hits planned diamond and tracks to the corner mouth.',
  },
  {
    id: 'sotd-28',
    name: 'Soft Safety: Hide Behind the 8',
    tagline: 'Legal hit + CB death behind the money ball',
    difficulty: 'Medium',
    category: 'kick',
    table: 'Open table safety',
    setup: [
      'Your OB free; 8 in center.',
      'Goal: thin your OB then park CB behind the 8.',
    ],
    objectBall: 'Your ball (thin)',
    pocket: 'None',
    tipZone: 'center',
    tipDetail: 'Center soft.',
    english: 'None or slight drag.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather touch.',
    bridge: 'Soft grip pressure.',
    steps: [
      'Plan thin contact that barely moves your OB.',
      'CB path should die behind the 8.',
      'Execute the softest legal stroke you can control.',
    ],
    tips: ['Great league shot — earns more racks than trick shots.'],
    commonMistakes: ['Moving your OB too far and leaving a duck.'],
    successLooksLike: 'Opponent is hooked or has a terrible kick.',
  },
  {
    id: 'sotd-29',
    name: 'Elevated Draw Over a Rail Nip',
    tagline: 'Slight elevation + low tip when the rail crowds you',
    difficulty: 'Hard',
    category: 'position',
    table: 'CB near rail, need draw',
    setup: [
      'CB within a few inches of a rail; OB straight-ish ahead.',
      'Standard low bridge is cramped — elevate slightly.',
    ],
    objectBall: 'Any short pot',
    pocket: 'Near pocket',
    tipZone: '6-low',
    tipDetail: 'Low tip with modest elevation.',
    english: 'None.',
    elevation: '10–20 degrees to clear the rail.',
    speed: 'soft',
    speedDetail: 'Soft–medium draw.',
    bridge: 'Rail bridge elevated.',
    steps: [
      'Rail bridge, elevate just enough.',
      'Low tip, soft stroke, stay quiet at impact.',
    ],
    tips: ['Mechanical bridge is legal and smart — ego freezes more balls than bridges do.'],
    commonMistakes: ['Over-elevating and scooping.'],
    successLooksLike: 'Pot + CB draws away from the rail crowding.',
  },
  {
    id: 'sotd-30',
    name: 'Clockwise Curve Drag',
    tagline: 'High-right roll that bends late',
    difficulty: 'Medium',
    category: 'curve',
    table: 'Longish shot with slight arc needed',
    setup: [
      'OB almost straight but a blocker forces a gentle right bend.',
      'CB mid-table.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: '1:30-high-right',
    tipDetail: 'High-right quadrant, half tip off axes.',
    english: 'Right + roll.',
    elevation: 'Level to 10°.',
    speed: 'soft',
    speedDetail: 'Soft so curve develops.',
    bridge: 'Open.',
    steps: [
      'Aim as if slightly left of pure line; spin brings it back.',
      'Soft high-right stroke.',
    ],
    tips: ['Mark start and end CB path with paper markers off the cloth edge for feedback.'],
    commonMistakes: ['Firm speed that kills curve.'],
    successLooksLike: 'Visible late bend into the OB line.',
  },
  {
    id: 'sotd-31',
    name: 'Three-Ball Line Combo',
    tagline: 'Centers stacked like a runway',
    difficulty: 'Medium',
    category: 'combo',
    table: 'Three in a line to corner',
    setup: [
      'Balls C (near pocket), B, A lined toward corner.',
      'CB on the line extended behind A.',
    ],
    objectBall: 'A→B→C',
    pocket: 'Corner for C',
    tipZone: 'center',
    tipDetail: 'Center stun.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — multi-ball combos amplify error with speed.',
    bridge: 'Open.',
    steps: [
      'Align all centers with one eye closed for a second — check the line.',
      'Soft center hit on A.',
    ],
    tips: ['If C misses left, the whole line was rotated — fix setup, not stroke.'],
    commonMistakes: ['Hitting hard “to make sure.”'],
    successLooksLike: 'Domino transfer; C drops.',
  },
  {
    id: 'sotd-32',
    name: 'Jump-Draw Hybrid Tease',
    tagline: 'Advanced: small hop then draw (use jump cue)',
    difficulty: 'Insane',
    category: 'jump',
    table: 'Short hop over chalk cube then draw',
    setup: [
      'Place a chalk cube as a mini obstacle (remove after — protect cloth).',
      'Better: use a donut paper ring as “virtual” obstacle and practice jump then separate draw drills.',
    ],
    objectBall: 'Short pot',
    pocket: 'Near corner',
    tipZone: '6-low',
    tipDetail: 'Low tip after a small jump is expert-only; prefer split practice.',
    english: 'None.',
    elevation: 'Jump elevation then normal for draw reps.',
    speed: 'firm',
    speedDetail: 'Firm jump dart.',
    bridge: 'Jump dart grip.',
    steps: [
      'Practice jump alone until clean.',
      'Practice draw alone.',
      'Only then attempt sequenced hybrid on open table.',
    ],
    tips: ['This is a long-term skill quest, not one session.'],
    commonMistakes: ['Combining both before either is solid — miscue city.'],
    successLooksLike: 'CB clears a low obstacle and still draws after landing (rare — celebrate progress).',
  },
  {
    id: 'sotd-33',
    name: 'Hold-Up English Along the Rail',
    tagline: 'Slide the CB up-table with reverse after a rail first',
    difficulty: 'Hard',
    category: 'position',
    table: 'Rail-first natural',
    setup: [
      'CB rail-first into OB near side for a natural.',
      'Need CB to hold up-table instead of racing forward.',
    ],
    objectBall: 'Side-pocket natural',
    pocket: 'Side',
    tipZone: '7:30-low-left',
    tipDetail: 'Low + outside/reverse depending on side — start half tip low-left or low-right.',
    english: 'Hold-up / reverse relative to CB travel.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium.',
    bridge: 'Closed.',
    steps: [
      'Pocket the natural with planned reverse.',
      'Watch CB refuse to race forward.',
    ],
    tips: ['Map both table sides; reverse side flips with direction.'],
    commonMistakes: ['Too much reverse → miscue or missed natural.'],
    successLooksLike: 'Natural drops; CB stays mid-table for next shot.',
  },
  {
    id: 'sotd-34',
    name: 'Dead Ball Bank (Soft)',
    tagline: 'Bank that dies in the pocket without rattle',
    difficulty: 'Medium',
    category: 'bank',
    table: 'Cross side bank',
    setup: [
      'OB off long rail banking to opposite side pocket.',
      'CB full hit available.',
    ],
    objectBall: 'Any',
    pocket: 'Opposite side',
    tipZone: 'center',
    tipDetail: 'Center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Softer than you think for side banks.',
    bridge: 'Open.',
    steps: [
      'Aim bank line.',
      'Soft center hit — let the pocket catch it.',
    ],
    tips: ['Side pockets are shallow; soft is your friend.'],
    commonMistakes: ['Firm bank that flies past the mouth.'],
    successLooksLike: 'Quiet drop in the side — no clack-rattle drama.',
  },
  {
    id: 'sotd-35',
    name: 'Point-to-Point Long Pot',
    tagline: 'Diamond to diamond straight aim training',
    difficulty: 'Easy',
    category: 'position',
    table: 'OB on foot spot, CB on head spot line',
    setup: [
      'Classic long pot: centers aligned head to foot.',
      'No english day — purity only.',
    ],
    objectBall: 'Any',
    pocket: 'Foot corner',
    tipZone: 'center',
    tipDetail: 'Dead center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium consistent.',
    bridge: 'Your match bridge.',
    steps: [
      'Pre-shot routine: stand, aim, down, feather, go.',
      'Center tip every rep.',
      'Make 7/10 before leaving the drill.',
    ],
    tips: ['This is the foundation under every trick shot on this list.'],
    commonMistakes: ['Skipping routine on “easy” long pots.'],
    successLooksLike: 'Boring, repeatable long pots — the real flex.',
  },
  {
    id: 'sotd-36',
    name: 'Jump-Kick Hybrid Plan',
    tagline: 'Choose jump OR kick — decide before you stroke',
    difficulty: 'Hard',
    category: 'kick',
    table: 'Blocked center',
    setup: [
      'Blocker dead on the line.',
      'OB past it near a corner.',
      'You may jump or one-rail kick — pick one strategy and commit.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: 'center',
    tipDetail: 'Center for both skills today.',
    english: 'None.',
    elevation: 'Level for kick; elevated only if jumping.',
    speed: 'firm',
    speedDetail: 'Firm for kick systems; dart for jump.',
    bridge: 'Match the choice.',
    steps: [
      'Take 5 kick attempts with diamond aim.',
      'Take 5 jump attempts (if equipment/room safe).',
      'Note which wins on your cloth — that’s your match plan.',
    ],
    tips: ['Pros pick the higher percentage option, not the cooler one.'],
    commonMistakes: ['Changing plan mid-stroke.'],
    successLooksLike: 'You know your go-to escape when snookered next league night.',
  },
  {
    id: 'sotd-37',
    name: 'Spin-to-Win Rail First',
    tagline: 'Running english stretches a rail-first natural',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Rail-first to side',
    setup: [
      'CB must hit long rail before OB for a natural side pocket.',
      'Need wider angle — running english helps.',
    ],
    objectBall: 'Side natural',
    pocket: 'Side',
    tipZone: '3-right',
    tipDetail: 'Running english: tip in the direction that accelerates along the rail after contact.',
    english: 'Running (forward along rail path).',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium.',
    bridge: 'Closed.',
    steps: [
      'Identify running side for your CB path.',
      'Half tip running, medium stroke into the rail first.',
      'Collect the natural.',
    ],
    tips: ['If the angle widens too much, reduce english before changing aim wildly.'],
    commonMistakes: ['Confusing reverse and running — sketch the CB path on paper first.'],
    successLooksLike: 'Rail-first natural that wouldn’t exist with center ball.',
  },
  {
    id: 'sotd-38',
    name: 'The Spotlight 8 Cut',
    tagline: 'Pressure cut: pretend it’s hill-hill',
    difficulty: 'Medium',
    category: 'position',
    table: '8 mid-table, toughish cut',
    setup: [
      '8-ball with a 35–45° cut to corner.',
      'CB clean.',
      'Add pressure: only one stroke attempt, then reset (simulate match nerves).',
    ],
    objectBall: '8-ball',
    pocket: 'Corner',
    tipZone: 'center',
    tipDetail: 'Center under pressure — simplify.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium pocket speed.',
    bridge: 'Match routine.',
    steps: [
      'Full routine. No rushed downs.',
      'Ghost ball aim.',
      'One intentional stroke. Win or reset — no “fix” babying.',
    ],
    tips: ['Breathe out on the stroke. Heart rate is a real variable.'],
    commonMistakes: ['Second-guessing mid-down.'],
    successLooksLike: '8 drops; you walk like it was always easy.',
  },
  {
    id: 'sotd-39',
    name: 'Quad Rail Dream (Path Only)',
    tagline: 'Four-rail CB path for shape geeks — pocket optional',
    difficulty: 'Insane',
    category: 'kick',
    table: 'Open table path practice',
    setup: [
      'CB only at start; no OB required for path training.',
      'Plan a four-rail CB tour that ends near the foot spot.',
    ],
    objectBall: 'None (path shot)',
    pocket: 'N/A',
    tipZone: '12-high',
    tipDetail: 'High center or slight running to keep rails lively.',
    english: 'Slight running as needed.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail.',
    bridge: 'Long.',
    steps: [
      'Call four rail contacts in order.',
      'Execute; mark where CB dies.',
      'Adjust first rail aim until the end zone is near the foot spot.',
    ],
    tips: ['This builds kick IQ faster than random kicking at balls.'],
    commonMistakes: ['Random blasting without named contacts.'],
    successLooksLike: 'CB hits four rails and parks near your called end zone.',
  },
  {
    id: 'sotd-40',
    name: 'Celebration Combo Off Two',
    tagline: 'End the cycle with a crowd-pleasing combo bank hybrid',
    difficulty: 'Hard',
    category: 'combo',
    table: 'Combo into a bank',
    setup: [
      'Ball A hits ball B into a rail then pocket.',
      'Line A–B carefully; bank portion uses center tip only.',
    ],
    objectBall: 'A→B bank',
    pocket: 'Corner after B’s bank',
    tipZone: 'center',
    tipDetail: 'Center through the whole chain.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — enough for the bank leg.',
    bridge: 'Closed.',
    steps: [
      'Set combo line for B’s bank entry angle.',
      'Soft–medium center hit on A.',
      'Watch B take the rail to the corner.',
    ],
    tips: ['If the bank is missed, freeze the setup and adjust B’s pre-rail position, not your ego stroke.'],
    commonMistakes: ['Too much speed on the combo transfer.'],
    successLooksLike: 'Combo-bank drops — save the clip for Memories.',
  },

  // ---------------------------------------------------------------------------
  // Artistic / exhibition-style shots (inspired by public show repertoires of
  // legends like Mike Massey & Florian "Venom" Kohler — originals for practice,
  // not licensed routines. Prop use is optional; prioritize cloth safety.)
  // ---------------------------------------------------------------------------
  {
    id: 'sotd-41',
    name: 'Butterfly Spread',
    tagline: 'Massey-style wing: two outer balls fly to opposite corners',
    difficulty: 'Hard',
    category: 'novelty',
    table: 'Three-ball butterfly on the foot spot',
    setup: [
      'Center ball on the foot spot (the “body”).',
      'Left wing ball ~½ diamond off center toward left corner line.',
      'Right wing ball mirrored toward right corner.',
      'CB in the kitchen, straightish into the center ball.',
    ],
    objectBall: 'Center ball (transfer into both wings)',
    pocket: 'Both corners — wings simultaneously if perfect',
    tipZone: 'center',
    tipDetail: 'Dead center for even energy left/right.',
    english: 'None. Any side spin biases one wing.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm, even stroke — both wings need similar pace.',
    bridge: 'Closed, locked.',
    steps: [
      'Square the wings so distances to each corner are equal.',
      'Hit the center ball full and square with center tip.',
      'Follow through straight; do not steer after contact.',
      'Watch both wings race toward opposite corners.',
    ],
    tips: [
      'Start with wings closer; widen as make rate climbs.',
      'Film from the foot of the table — classic exhibition angle.',
    ],
    commonMistakes: [
      'Hitting left or right of center on the CB — one wing dies.',
      'Wings not mirrored — fix geometry before blaming stroke.',
    ],
    successLooksLike: 'Both wing balls drop opposite corners on the same stroke.',
  },
  {
    id: 'sotd-42',
    name: 'Machine-Gun Line',
    tagline: 'Venom energy: rip a straight line of balls in sequence',
    difficulty: 'Hard',
    category: 'combo',
    table: '4–5 balls in a tight line to a corner',
    setup: [
      'Line 4 balls toward a corner, nearly touching (¼ inch gaps OK for learning).',
      'CB on the extended line, 1 diamond behind the first ball.',
    ],
    objectBall: 'Chain through the line',
    pocket: 'Corner for the last ball',
    tipZone: 'center',
    tipDetail: 'Center stun so the chain does not throw offline.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium-firm — enough to carry the chain, not so hard it sprays.',
    bridge: 'Open, chin low.',
    steps: [
      'Sight centers of all balls as one runway into the pocket.',
      'Soft-to-medium center hit on ball 1.',
      'Hold still — the “machine gun” is the rapid transfer sound.',
    ],
    tips: ['If the last ball misses left, the whole line was rotated — rebuild setup.'],
    commonMistakes: ['Hero speed that throws the end ball offline.'],
    successLooksLike: 'Rapid-fire transfers; last ball drops clean.',
  },
  {
    id: 'sotd-43',
    name: 'Squeeze Between Friends',
    tagline: 'Classic squeeze: CB threads a gap you “shouldn’t” fit',
    difficulty: 'Insane',
    category: 'novelty',
    table: 'Two blockers with a tight gate',
    setup: [
      'Two object balls almost blocking a path to a third OB near a corner.',
      'Gap slightly wider than a ball — CB must go through without a foul double-kiss disaster.',
      'CB with a clear soft line into the gate.',
    ],
    objectBall: 'Target beyond the gate',
    pocket: 'Corner for target',
    tipZone: 'center',
    tipDetail: 'Center and soft — control over flair.',
    english: 'None on first successful reps.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather. Squeeze shots die when overhit.',
    bridge: 'Long, quiet.',
    steps: [
      'Pick the exact gap centerline.',
      'Feather the CB through the gate into the target.',
      'Celebrate not touching blockers more than the pot itself.',
    ],
    tips: ['Widen the gap until you make 5/10, then tighten — exhibition builders do this.'],
    commonMistakes: ['Aiming the pot first instead of clearing the gate.'],
    successLooksLike: 'CB slips the gate and pots the target clean.',
  },
  {
    id: 'sotd-44',
    name: 'Around-the-World CB Tour',
    tagline: 'Exhibition path shot: multi-rail CB ends on a dime',
    difficulty: 'Hard',
    category: 'kick',
    table: 'Open table, CB only path practice then add OB',
    setup: [
      'Call 3–4 rail contacts that return CB near the head spot.',
      'Optional finish: soft contact a hanging OB into a corner after the tour.',
    ],
    objectBall: 'Optional hangar after path',
    pocket: 'Optional corner',
    tipZone: '12-high',
    tipDetail: 'High center / slight running to keep cushions lively.',
    english: 'Slight running as needed for the last rails.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail pace.',
    bridge: 'Long.',
    steps: [
      'Name each rail diamond before you shoot.',
      'Firm high-center stroke into rail 1.',
      'Track the tour; adjust only first-rail aim between reps.',
    ],
    tips: ['Massey exhibitions sell the path — call it out loud for the camera.'],
    commonMistakes: ['Random power without named diamonds.'],
    successLooksLike: 'CB hits every called rail and parks in the end zone (hangar pot is gravy).',
  },
  {
    id: 'sotd-45',
    name: 'Elevator Jump Over the Rack Ghost',
    tagline: 'Jump clear of a “rack width” obstacle (use safe props)',
    difficulty: 'Insane',
    category: 'jump',
    table: 'Jump over a rolled towel or jump trainer — never risk deep cloth tears',
    setup: [
      'Place a low soft obstacle (towel roll / jump aid), not a full heavy rack on good cloth.',
      'OB just beyond; CB needs a clean hop and land before contact.',
      'Jump cue strongly preferred.',
    ],
    objectBall: 'Short target beyond obstacle',
    pocket: 'Near corner preferred',
    tipZone: 'center',
    tipDetail: 'Center of CB, strike down.',
    english: 'None.',
    elevation: '45–60° with jump cue.',
    speed: 'firm',
    speedDetail: 'Short firm dart — height comes from elevation + acceleration, not body heave.',
    bridge: 'Dart grip above the ball.',
    steps: [
      'Clear the area; protect cloth and lights.',
      'Dart into the top of the CB; jump the obstacle.',
      'Land and contact OB without scooping.',
    ],
    tips: ['Venom-level jumps are years of reps — log height before adding distance.'],
    commonMistakes: ['Scoop foul. Always hit down into the ball.'],
    successLooksLike: 'CB clears the obstacle and still makes a legal hit / pot.',
  },
  {
    id: 'sotd-46',
    name: 'Snake Along the Rail',
    tagline: 'Multiple soft rail kisses walking a ball to the pocket',
    difficulty: 'Hard',
    category: 'bank',
    table: 'OB near long rail “snaking” toward corner',
    setup: [
      'OB a ball off the long rail, CB set to send it into rail → out → rail → corner.',
      'Think gentle zigzag, not one big bank.',
    ],
    objectBall: 'Any',
    pocket: 'Downstream corner',
    tipZone: 'center',
    tipDetail: 'Center for predictable first rail.',
    english: 'None until the snake is consistent.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium so multi-rail path doesn’t fly.',
    bridge: 'Open.',
    steps: [
      'Plan two rail contacts before the pocket.',
      'Soft center hit to start the snake.',
      'Adjust first rail if the second contact overshoots.',
    ],
    tips: ['Exhibition snake shots look magical when speed is quiet.'],
    commonMistakes: ['One hard bank instead of a controlled multi-kiss path.'],
    successLooksLike: 'OB rails more than once and dies in the corner.',
  },
  {
    id: 'sotd-47',
    name: 'Coin Prop Freeze (Optional Prop)',
    tagline: 'Massey-adjacent prop precision: freeze OB to a marker',
    difficulty: 'Hard',
    category: 'novelty',
    table: 'Use a paper marker / chalk ring — coins only if house allows',
    setup: [
      'Place a flat marker on the cloth as a “target pad” near a pocket line.',
      'Shoot an OB to stop dead on/against the marker after a soft stun.',
      'CB one diamond away, straight.',
    ],
    objectBall: 'Any',
    pocket: 'Optional; primary goal is freeze accuracy',
    tipZone: 'center',
    tipDetail: 'Stun center so OB dies on the pad.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather stun — measure distance carefully.',
    bridge: 'Quiet open bridge.',
    steps: [
      'Align centers through the marker.',
      'Feather center stun into the OB.',
      'OB should stop kissing the marker.',
    ],
    tips: ['Precision props train pace better than pots alone.'],
    commonMistakes: ['Overhit — OB skates past the prop.'],
    successLooksLike: 'OB freezes on the marker like it was glued.',
  },
  {
    id: 'sotd-48',
    name: 'Swing-Cut Showboat',
    tagline: 'Big outside cut that “swings” CB for shape',
    difficulty: 'Hard',
    category: 'position',
    table: 'Wide cut with dramatic CB swing',
    setup: [
      'OB near corner with a 50°+ cut.',
      'CB positioned so a successful cut sends CB swinging up-table along a showy arc.',
    ],
    objectBall: 'Any',
    pocket: 'Corner',
    tipZone: '3-right',
    tipDetail: 'Often slight outside (adjust side to cut) — start center, then add half tip outside.',
    english: 'Outside half tip after center makes.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium pocket speed; let the cut create the swing.',
    bridge: 'Closed.',
    steps: [
      'Make the cut with center first (no swing pressure).',
      'Add outside english to widen CB swing for the camera.',
      'Stay down — the swing is post-contact theater.',
    ],
    tips: ['Exhibition is make % first, flair second.'],
    commonMistakes: ['Spin before you can pot the cut.'],
    successLooksLike: 'OB drops; CB sweeps a wide, clean arc up-table.',
  },
  {
    id: 'sotd-49',
    name: 'Impossible-Looking Thin Cut',
    tagline: 'Artistic pool energy: cut that looks illegal',
    difficulty: 'Insane',
    category: 'position',
    table: 'Ultra-thin cut along a rail',
    setup: [
      'OB frozen or nearly frozen on long rail.',
      'CB almost straight behind it but needing a micro-thin cut into the corner.',
      'Leave a visible “edge only” aim.',
    ],
    objectBall: 'Rail ball',
    pocket: 'Downstream corner',
    tipZone: 'center',
    tipDetail: 'Center tip; thin cuts + spin = chaos.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather. Anything firmer rattles or rails wrong.',
    bridge: 'Long, low, zen.',
    steps: [
      'See only a sliver of the OB.',
      'Breathe out; feather center stroke.',
      'Trust the micro-contact.',
    ],
    tips: ['If you can’t see a sliver, you’re aiming a miss — reset geometry.'],
    commonMistakes: ['Hit-and-hope power.'],
    successLooksLike: 'OB barely moves sideways and still falls — crowd gasps optional.',
  },
  {
    id: 'sotd-50',
    name: 'Venom-Style Jump-Curve Tease',
    tagline: 'Small hop then swerve — advanced only',
    difficulty: 'Insane',
    category: 'jump',
    table: 'Open table skill quest',
    setup: [
      'Short jump over a soft low obstacle, then need slight curve to OB.',
      'Prefer separate practice: 10 jumps, 10 swerves, then combine once a week.',
    ],
    objectBall: 'Offset OB after landing zone',
    pocket: 'Near corner',
    tipZone: '1:30-high-right',
    tipDetail: 'Jump with center; curve leg uses high-side after you can land consistently.',
    english: 'Side only on the curve-only drills until ready.',
    elevation: 'Jump elevation for hop; level for pure swerve reps.',
    speed: 'firm',
    speedDetail: 'Firm dart for jump; soft for swerve practice.',
    bridge: 'Jump dart / elevated soft bridge for swerve.',
    steps: [
      'Master landing zone with center jump.',
      'Master swerve path without jump.',
      'Combine only when both are 70%+.',
    ],
    tips: [
      'This is multi-month repertoire material — log sessions in Memories.',
      'Cloth safety > clout.',
    ],
    commonMistakes: ['Combining skills too early and scuffing cloth.'],
    successLooksLike: 'CB hops, lands, bends, and still finds the OB line.',
  },
  {
    id: 'sotd-51',
    name: 'Massey Mirror Banks',
    tagline: 'Symmetric two-bank challenge — left then right',
    difficulty: 'Hard',
    category: 'bank',
    table: 'Mirror bank pair',
    setup: [
      'Set a cross-side bank from the left half of the table; make 3.',
      'Immediately mirror the identical bank from the right half.',
      'Score only if both sides work in one session.',
    ],
    objectBall: 'Any (reset mirror each side)',
    pocket: 'Side pocket via bank',
    tipZone: 'center',
    tipDetail: 'Center both sides — symmetry trains aim systems.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Same speed both sides — that’s the point.',
    bridge: 'Match bridge both ways.',
    steps: [
      'Bank left→side with called diamond and fixed speed.',
      'Mirror right→side with the same speed.',
      'Only change aim, not stroke tempo.',
    ],
    tips: ['Exhibition consistency is bilateral — weak side exposes you.'],
    commonMistakes: ['Changing speed when the second side misses.'],
    successLooksLike: 'Both mirrors drop with the same stroke rhythm.',
  },
  {
    id: 'sotd-52',
    name: 'Rapid-Fire Spot Shots',
    tagline: 'Show pace: same pot, 10 times, no walk-around',
    difficulty: 'Medium',
    category: 'novelty',
    table: 'OB on spot, CB in kitchen',
    setup: [
      'OB replaced on foot spot every rep (partner or self-spot).',
      'CB returned to the same kitchen mark.',
      'Goal: 8/10 in under two minutes.',
    ],
    objectBall: 'Spot ball',
    pocket: 'Chosen corner — stick with one',
    tipZone: 'center',
    tipDetail: 'Center only — speedrun accuracy.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'One pre-chosen medium speed for all 10.',
    bridge: 'Your fastest stable routine.',
    steps: [
      'Mark CB and OB with chalk dots off-cloth references.',
      'Fire 10 strokes with full routine shortened but not skipped.',
      'Count makes; reset tomorrow if under 8.',
    ],
    tips: ['Exhibition polish is tempo under control, not rushed mess.'],
    commonMistakes: ['Skipping chalk and miscueing for “speed.”'],
    successLooksLike: '8+ pots, same corner, same pace — highlight ready.',
  },
];

export function catalogLength(): number {
  return SHOT_CATALOG.length;
}

export function getShotById(id: string): CatalogShot | undefined {
  return SHOT_CATALOG.find((s) => s.id === id);
}

export function getShotByIndex(index: number): CatalogShot {
  const i = ((index % SHOT_CATALOG.length) + SHOT_CATALOG.length) % SHOT_CATALOG.length;
  return SHOT_CATALOG[i];
}