/**
 * Curated trick / skill shots for Shot of the Day.
 * Contact zones use a clock face on the cue ball (player view):
 * 12 = high (follow), 6 = low (draw), 3 = right english, 9 = left english, center = stun.
 */

/**
 * Position convention used by every shot (setup lines, pockets, routes) and by the diagrams:
 *
 *  - Head = the break end (head rail, head string, head spot); foot = the racking end
 *    (foot rail, foot string, foot spot).
 *  - Left and right are as you stand at the head rail facing the foot. So the two long rails
 *    are the left long rail and the right long rail, and the six pockets are the head-left,
 *    head-right, foot-left and foot-right corners and the left and right side pockets.
 *  - Lines: head string (2 diamonds from the head rail), center string (side pockets),
 *    foot string (2 diamonds from the foot rail), long string (head spot → foot spot).
 *    Spots: head spot, center spot, foot spot.
 *  - Distances are measured to the ball’s centre: from the cushion nose for rails, centre to
 *    centre between balls, to the pocket point for pockets. 1 diamond = 12.5 in on a 9 ft table.
 *  - Frozen = touching (the rail or the named ball). Half a ball off the rail = the ball’s
 *    centre 2.25 in from the cushion (a half-ball gap). "N-inch gap" = cloth between two balls.
 *  - "Route:" lines list what the moving balls touch, in order: CB → rails → balls → pocket.
 *  - Diagrams draw only balls; a jump hop is one straight dashed line from takeoff to landing,
 *    directly over the jumped ball, and every rolling segment is solid.
 */
export const SHOT_POSITION_CONVENTION: readonly string[] = [
  'Head = the break end; foot = the racking end.',
  'Left and right are as you stand at the head rail facing the foot (left long rail, right long rail).',
  'Pockets: head-left, head-right, foot-left, foot-right corners; left and right side pockets.',
  'Head string, center string, foot string and long string; head spot, center spot, foot spot.',
  'Distances are to the ball’s centre; 1 diamond = 12.5 inches on a 9-foot table.',
  'Frozen = touching. Half a ball off the rail = centre 2.25 inches from the cushion.',
  'Route lines read CB → rails → balls → pocket, in the order they are touched.',
  'Jumps: one straight dashed hop from takeoff to landing, directly over the jumped ball.',
];

export type TipZone =
  | 'center'
  | '12-high'
  | '6-low'
  | '3-right'
  | '9-left'
  | '1:30-high-right'
  | '10:30-high-left'
  | '4:30-low-right'
  | '7:30-low-left';

export type StrokeSpeed = 'feather' | 'soft' | 'medium' | 'firm' | 'power';

export type ShotDifficulty = 'Easy' | 'Medium' | 'Hard' | 'Insane';

export type ShotCategory =
  | 'bank'
  | 'combo'
  | 'curve'
  | 'jump'
  | 'masse'
  | 'kick'
  | 'carom'
  | 'novelty'
  | 'position';

export type CatalogShot = {
  id: string;
  name: string;
  tagline: string;
  /** One plain sentence: what the shot does on the table. */
  what?: string;
  /** One plain sentence: what the shot trains / when you use it. */
  why?: string;
  difficulty: ShotDifficulty;
  category: ShotCategory;
  table: string;
  setup: string[];
  objectBall: string;
  pocket: string;
  tipZone: TipZone;
  tipDetail: string;
  english: string;
  elevation: string;
  speed: StrokeSpeed;
  speedDetail: string;
  bridge: string;
  steps: string[];
  tips: string[];
  commonMistakes: string[];
  successLooksLike: string;
};

export const SHOT_CATALOG: CatalogShot[] = [
  {
    id: 'sotd-01',
    name: 'Cross-Side Bank',
    tagline: 'Cross-side bank off the right long rail that trains bank geometry',
    what: 'Bank the 1 off the right long rail, straight across the table into the left side pocket.',
    why: 'Trains you to read bank angles with a mirror or diamond system instead of guessing.',
    difficulty: 'Medium',
    category: 'bank',
    table: '9-foot; 1-ball on the foot string, half a ball off the right long rail',
    setup: [
      '1-ball: on the foot string, half a ball off the right long rail.',
      'Cue ball: on the long string, one diamond from the foot rail.',
      'Route: CB → 1-ball → right long rail → left side pocket.',
    ],
    objectBall: '1-ball',
    pocket: 'Left side pocket, banked off the right long rail',
    tipZone: 'center',
    tipDetail: 'Hit dead center of the cue ball — pure stun transfer into the bank.',
    english: 'None. Spin ruins bank angle prediction.',
    elevation: 'Level cue. Keep the stick flat.',
    speed: 'medium',
    speedDetail: 'Medium firm — enough to hold the rail line, not so hard it compresses the cushion wrong.',
    bridge: 'Open bridge, stable, chin 2 inches above the stick.',
    steps: [
      'Stand so your aim line is object-ball center → mirror system across the rail.',
      'Use equal-diamond or 1.5× system: contact the rail so rebound aims the side pocket.',
      'Center-ball tip. Pause at the back of the stroke.',
      'Deliver a smooth medium stroke with a 6–8 inch follow-through.',
      'Stay down until the object ball hits the rail.',
    ],
    tips: [
      'If the bank runs long (toward the head), move your rail aim point 1 inch toward the foot.',
      'Cloth speed changes the bank angle: fix your speed first, then adjust aim in 1-inch steps.',
    ],
    commonMistakes: [
      'Hitting low/high on the CB and changing natural roll into the cushion.',
      'Steering with the tip through contact.',
    ],
    successLooksLike: 'The 1 hits the right long rail once and drops in the center of the left side pocket.',
  },
  {
    id: 'sotd-02',
    name: 'Stop-Shot Ladder',
    tagline: 'Dead-center stun that freezes the cue ball',
    what: 'Pot a straight-in ball with a center hit so the cue ball stops dead where it made contact.',
    why: 'Builds the stop shot, the base of all cue-ball control.',
    difficulty: 'Easy',
    category: 'position',
    table: 'Straight shot from the foot spot to the foot-right corner',
    setup: [
      '1-ball: on the foot spot.',
      'Cue ball: one diamond from the 1, straight in behind it toward the foot-right corner.',
      'Clear path; no rail first.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Exact center of the cue ball for pure stun at impact.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium so the CB arrives sliding, not rolling.',
    bridge: 'Closed bridge optional for control.',
    steps: [
      'Align centers: CB → OB → pocket.',
      'Short backstroke, accelerate smoothly into center.',
      'Stop the tip just past the CB — no scoop.',
      'Watch the CB freeze in place as the OB goes.',
    ],
    tips: ['If CB rolls forward after, you hit too high or too soft from too far.'],
    commonMistakes: ['Elevating the cue and scooping under the ball.'],
    successLooksLike: 'The 1 pockets; the cue ball stops within a hand-span (6 inches) of the contact point.',
  },
  {
    id: 'sotd-03',
    name: 'Draw Back Two Diamonds',
    tagline: 'Low tip, soft speed, big return',
    what: 'Pot a straight ball with a low hit so the cue ball draws straight back two diamonds.',
    why: 'Teaches clean draw so you can pull the cue ball back for your next shot.',
    difficulty: 'Medium',
    category: 'position',
    table: 'Straight shot from the foot spot to the foot-right corner',
    setup: [
      '1-ball: on the foot spot.',
      'Cue ball: one diamond from the 1, straight in behind it toward the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '6-low',
    tipDetail: 'Tip a half-ball below center — low enough for draw, not so low you miscue.',
    english: 'None. Pure backspin.',
    elevation: 'Level cue; the tip strikes half a ball below center.',
    speed: 'soft',
    speedDetail: 'Soft but crisp. Draw needs spin retention more than raw power.',
    bridge: 'Open or closed; keep wrist quiet.',
    steps: [
      'Chalk thoroughly — draw miscues are tip/chalk failures.',
      'Aim center-to-center for a straight pocket.',
      'Contact the CB at 6 o’clock, accelerate through.',
      'Follow through low; don’t lift early.',
      'The CB should come straight back two diamonds after contact.',
    ],
    tips: ['Closer CB → more reliable draw. Start at one diamond, then lengthen.'],
    commonMistakes: ['Power stroke that skids without reversing.', 'Hitting left/right and curving off line.'],
    successLooksLike: 'The 1 drops in the foot-right corner; the CB draws straight back two diamonds (25 inches).',
  },
  {
    id: 'sotd-04',
    name: 'Follow Into the Stack',
    tagline: 'High tip rolls the cue ball into the 2 and 3 on purpose',
    what: 'Pot the 1 with a high hit and let the cue ball roll on into the 2 and 3.',
    why: 'Teaches controlled follow for breaking up a small cluster on purpose.',
    difficulty: 'Easy',
    category: 'position',
    table: 'Three balls at the foot end; cue ball on the head string',
    setup: [
      '1-ball: on the foot string, one diamond from the left long rail.',
      '2-ball: one diamond from the 1, on the cue ball’s roll-on line toward the foot rail.',
      '3-ball: frozen to the 2.',
      'Cue ball: on the head string, two diamonds from the right long rail; 12° cut on the 1 into the foot-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: '12-high',
    tipDetail: 'Tip a half-ball above center for natural roll follow.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — carry roll into the next ball without flying the table.',
    bridge: 'Open bridge.',
    steps: [
      'Pocket the 1 with a high center hit.',
      'Let the CB roll forward into the 2 (it caroms on into the 3).',
      'Track where the CB finishes — the goal is controlled roll, not a blast.',
    ],
    tips: ['If you over-follow, soften speed before lowering the tip.'],
    commonMistakes: ['Hitting too high and miscueing over the top.'],
    successLooksLike: 'The 1 pockets; the CB rolls forward cleanly into the 2 and 3.',
  },
  {
    id: 'sotd-05',
    name: 'Inside English Cut',
    tagline: 'Throw the object ball with intentional spin',
    what: 'Cut the 1 into the corner with inside (same-side) english and aim thinner to allow for the throw.',
    why: 'Shows how side spin throws the object ball so you can adjust your aim for it.',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Half-ball cut into the foot-right corner',
    setup: [
      '1-ball: one diamond from the foot rail, one diamond from the right long rail.',
      'Cue ball: two diamonds from the 1, set for a 35° cut into the foot-right corner (the 1 goes right).',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '3-right',
    tipDetail: 'The 1 goes right into the pocket, so use right (inside) english: tip at 3 o’clock, half a tip off center.',
    english: 'Inside — same side as the cut direction through the CB.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium so throw has time to act.',
    bridge: 'Firm closed bridge recommended.',
    steps: [
      'Aim the plain ghost-ball cut, then shift the aim half an inch thinner: inside english throws the 1 fuller than the line you hit.',
      'Stroke straight — do not steer the tip sideways through the ball.',
      'Watch the throw: aimed thin, the 1 still drops in the center of the pocket.',
    ],
    tips: ['Practice both sides. Mirror: left cut → 9 o’clock tip.'],
    commonMistakes: ['Too much tip offset → miscue. Start with half a tip only.'],
    successLooksLike: 'Aimed half an inch thin, the 1 still drops in the center of the foot-right corner: inside-english throw pushed it fuller.',
  },
  {
    id: 'sotd-06',
    name: 'Outside English Hold',
    tagline: 'Kill the natural throw; hold the tangent',
    what: 'Cut the same ball with outside english to cancel throw and keep the cue ball on a tighter line.',
    why: 'Lets you steer the cue ball on cut shots without missing the pot.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Medium cut into the foot-right corner',
    setup: [
      '1-ball: one diamond from the foot rail, one diamond from the right long rail (the sotd-05 spot).',
      'Cue ball: two diamonds from the 1, set for a 30° cut into the foot-right corner (the 1 goes right).',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '9-left',
    tipDetail: 'Outside english: tip opposite the cut side — the 1 goes right, so tip at 9 o’clock (left), half a tip off center.',
    english: 'Outside, half tip.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium to reduce excessive throw while keeping spin.',
    bridge: 'Closed.',
    steps: [
      'Find the plain cut line.',
      'Apply outside english; it cancels cut-induced throw, so aim the exact ghost-ball line with no throw allowance.',
      'Smooth delivery — spin without a wrist flick.',
    ],
    tips: ['Outside is for CB path control more than pocketing — pocket first with center, then add spin.'],
    commonMistakes: ['Changing aim wildly; adjust in quarter-inch steps only.'],
    successLooksLike: 'The 1 pockets; the CB takes a tighter, less thrown tangent line than with center ball.',
  },
  {
    id: 'sotd-07',
    name: 'Two-Rail Kick to Corner',
    tagline: 'Two-rail kick for when the 8 blocks your line',
    what: 'Kick the cue ball off the left long rail, then the right long rail, into the 1 and send it into the foot-left corner.',
    why: 'Gives you a reliable two-rail kick system for when you’re snookered.',
    difficulty: 'Hard',
    category: 'kick',
    table: 'Cue ball at the head end; the 8 blocks the direct line to the 1',
    setup: [
      '1-ball: 1.5 diamonds from the foot rail, one diamond from the left long rail.',
      'Cue ball: one diamond from the head rail, one diamond from the left long rail.',
      '8-ball: halfway between the cue ball and the 1, blocking the direct hit.',
      'Route: CB → left long rail → right long rail → 1-ball → foot-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner (the pot is required)',
    tipZone: 'center',
    tipDetail: 'Center ball first — learn geometry before adding running english.',
    english: 'None on first reps. Later: running english to widen the angle off each rail.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm so multi-rail path holds, not so hard rails go dead.',
    bridge: 'Long bridge, stable.',
    steps: [
      'Mirror the 1 across the right long rail, then across the left long rail, to find the first-rail aim point.',
      'Pick the first-rail contact diamond with a two-rail kick system you know.',
      'Stroke center-ball, firm, through the first cushion.',
      'Track the second rail contact, then the 1.',
    ],
    tips: ['Mark the first-rail aim point with a chalk dot on the rail cap (not the cloth) for feedback.'],
    commonMistakes: ['Guessing without a system. Pick one system and stick to it for 20 reps.'],
    successLooksLike: 'The CB hits the left long rail, then the right long rail, then the 1; the 1 drops in the foot-left corner.',
  },
  {
    id: 'sotd-08',
    name: 'Simple Combo: Spot to Corner',
    tagline: 'Line the centers — combos are geometry',
    what: 'Shoot the 1 straight into the 2 so the 2 goes in the foot-left corner.',
    why: 'Teaches you to line up combinations by lining up ball centers.',
    difficulty: 'Easy',
    category: 'combo',
    table: 'Two-ball combo from the foot spot',
    setup: [
      '1-ball: on the foot spot.',
      '2-ball: one diamond from the 1, on the line from the 1 to the foot-left corner.',
      'Cue ball: one diamond from the 1, straight behind it on the same line.',
      'Route: CB → 1-ball → 2-ball → foot-left corner.',
    ],
    objectBall: '1-ball into the 2-ball',
    pocket: 'Foot-left corner (for the 2)',
    tipZone: 'center',
    tipDetail: 'Center stun so you don’t throw the combo line.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium; hard speed throws combos offline.',
    bridge: 'Open.',
    steps: [
      'Line up the centers of the 1 and 2 with the pocket — that line is sacred.',
      'Place the CB on the extension of that line.',
      'Shoot the 1 full into the 2 with a center tip.',
    ],
    tips: ['If the 2 misses left, the 1 hit the 2 too full or too thin — adjust the contact on the 2, not random english.'],
    commonMistakes: ['Looking at the pocket instead of the 1–2 contact.'],
    successLooksLike: 'The 2 drops; the 1 stops within 3 inches of where it hit the 2.',
  },
  {
    id: 'sotd-09',
    name: 'Carom Off the 9',
    tagline: 'Glance off the 9 and carom the cue ball into the 1',
    what: 'Glance the cue ball off the 9 so it caroms into the 1 and knocks the 1 into the foot-right corner.',
    why: 'Teaches you to predict the cue ball’s path after contact (the 30° rule) and use it on purpose.',
    difficulty: 'Medium',
    category: 'carom',
    table: 'Carom: the 9 first, then the 1 in front of the foot-right corner (call the 1; straight-pool rules allow any first ball)',
    setup: [
      '9-ball: 2.5 diamonds from the foot rail, 1.5 diamonds from the right long rail.',
      '1-ball: 5 inches from the foot rail and 3.5 inches from the right long rail, in front of the foot-right corner.',
      'Cue ball: 3 diamonds from the head rail, one diamond from the right long rail; a 30° cut on the 9 sends the CB along its carom line into the 1.',
      'Route: CB → 9-ball → 1-ball → foot-right corner.',
    ],
    objectBall: '9-ball first, then the cue ball caroms into the 1-ball',
    pocket: 'Foot-right corner (the 1)',
    tipZone: '12-high',
    tipDetail: 'One tip above center: follow keeps the CB rolling forward along the carom line.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft control — caroms need pace discipline.',
    bridge: 'Open.',
    steps: [
      'See the CB’s path after hitting the 9: the 30° carom line off a half-ball hit, bent forward by follow.',
      'Hit the 9 so that carom line runs through the 1 toward the foot-right corner.',
      'Soft stroke, one tip above center.',
    ],
    tips: ['Ghost-ball aim on the 9 while you plan the CB’s exit line.'],
    commonMistakes: ['Hitting the 9 too full: the carom line swings away from the 1. Film from above if you can.'],
    successLooksLike: 'The 9 rolls off toward the center of the table; the CB caroms into the 1 and the 1 drops in the foot-right corner.',
  },
  {
    id: 'sotd-10',
    name: 'Rail Cut Thin as Hair',
    tagline: 'Frozen rail thin cut — soft touch masterclass',
    what: 'Thin-cut a ball frozen on the rail so it creeps along the cushion into the corner.',
    why: 'Builds soft touch and confidence on thin rail cuts.',
    difficulty: 'Hard',
    category: 'position',
    table: '1-ball frozen to the right long rail on the foot string',
    setup: [
      '1-ball: frozen to the right long rail, on the foot string.',
      'Cue ball: two diamonds from the 1, set for a 55° cut into the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center tip; thin cut needs clean hit.',
    english: 'None. Add outside english only after 7 makes in 10.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather–soft. Hard thin cuts rattle jaws.',
    bridge: 'Long, stable, low.',
    steps: [
      'See a sliver of the 1 — aim to shave an eighth to a quarter of the ball.',
      'Soft center-ball stroke.',
      'Let the rail guide the 1: hit the cushion and the 1 together and it rolls along the cushion.',
    ],
    tips: ['If it rattles long, you were too thick or too hard.'],
    commonMistakes: ['Power stroke on a touch shot.'],
    successLooksLike: 'The 1 creeps along the rail and falls without a rattle.',
  },
  {
    id: 'sotd-11',
    name: 'Force Follow Over Distance',
    tagline: 'High tip + firm stroke = table-length follow',
    what: 'Pot a long 12° cut with high spin and firm speed so the cue ball rolls on two diamonds or more past contact.',
    why: 'Teaches follow that holds up over distance for long position moves.',
    difficulty: 'Medium',
    category: 'position',
    table: 'Long shot from the head string to the foot-left corner',
    setup: [
      '1-ball: on the foot string, 1.5 diamonds from the left long rail.',
      'Cue ball: on the head string, 7.5 inches from the right long rail; 12° cut on the 1 into the foot-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: '12-high',
    tipDetail: 'High center: a full tip above center, the highest contact that does not miscue.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm — you need roll to survive distance.',
    bridge: 'Open, elevated hand for comfort on high tip.',
    steps: [
      'Chalk well for high contact.',
      'Smooth acceleration; full follow-through high.',
      'The CB should travel 2 diamonds or more past the 1 after the pot.',
    ],
    tips: ['If you miscue, lower the tip half a tip and keep firm speed.'],
    commonMistakes: ['Jabbing; high tip needs a pure stroke.'],
    successLooksLike: 'OB pockets; CB continues forward 2+ diamonds past contact.',
  },
  {
    id: 'sotd-12',
    name: 'Power Draw Escape',
    tagline: 'Low tip, firm stroke, drag the CB home',
    what: 'Pot a straight ball and draw the cue ball back past the center of the table.',
    why: 'Gives you a big draw for getting out of trouble or back up the table.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Long draw into the foot-right corner',
    setup: [
      '1-ball: 1.5 diamonds from the foot rail, one diamond from the right long rail.',
      'Cue ball: 2.25 diamonds from the 1, straight in toward the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '6-low',
    tipDetail: 'Low as you dare with good chalk — full tip below center.',
    english: 'None.',
    elevation: 'Level to 5° down; no more.',
    speed: 'firm',
    speedDetail: 'Firm and crisp — not wild. Spin + speed both matter.',
    bridge: 'Closed bridge preferred.',
    steps: [
      'Chalk, breathe, low tip alignment check.',
      'Accelerate through the CB; long low follow-through.',
      'CB should rocket back toward the head of the table.',
    ],
    tips: ['Warm up with soft draw first — power draw is a finisher.'],
    commonMistakes: ['Scooping under the ball (foul territory / jump).'],
    successLooksLike: 'OB pockets; CB returns past the center string.',
  },
  {
    id: 'sotd-13',
    name: 'Bank the 9 Off Two Rails',
    tagline: 'Show-off bank for highlight reels',
    what: 'Bank the 9 off the right long rail, then the foot rail, the full length of the table into the head-left corner.',
    why: 'Stretches your bank geometry and speed control on two-rail banks.',
    difficulty: 'Insane',
    category: 'bank',
    table: '9 on the center string; bank right long rail → foot rail → head-left corner',
    setup: [
      '9-ball: on the center string, one diamond from the right long rail.',
      'Cue ball: 1.5 diamonds from the 9, set to drive the 9 into the right long rail first.',
      'Route: CB → 9-ball → right long rail → foot rail → head-left corner.',
    ],
    objectBall: '9-ball',
    pocket: 'Head-left corner, after two cushions',
    tipZone: 'center',
    tipDetail: 'Center ball for predictable bank angles.',
    english: 'None until consistent; then half a tip of running english.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail pace.',
    bridge: 'Solid closed.',
    steps: [
      'Plan rail1 and rail2 contacts with diamond system.',
      'Hit 9 full enough to take speed into rail1.',
      'Stay down — this shot rewards patience more than muscle.',
    ],
    tips: ['Call it only when you’ve made 3/10 in practice.'],
    commonMistakes: ['Too thin on 9 — dies on first rail.'],
    successLooksLike: 'The 9 takes two rails and drops in the head-left corner. Crowd optional.',
  },
  {
    id: 'sotd-14',
    name: 'Curve Around a Blocker',
    tagline: 'Massé-lite swerve around a ball that blocks your line',
    what: 'Swerve the cue ball around the 8, which sits on your direct line, so it bends back and pots the 1.',
    why: 'Gives you a gentle swerve for when a ball partly blocks the shot.',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Blocker ball halfway along the line',
    setup: [
      '1-ball: 2.4 diamonds from the foot-left corner, straight in to it.',
      'Cue ball: on the center string, 5 inches from the right long rail.',
      '8-ball: halfway between the cue ball and the 1, on the direct line, blocking a direct hit.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: '1:30-high-right',
    tipDetail: 'High-right, half a tip off center each way, cue elevated 20–30° for swerve.',
    english: 'One tip of right side plus half a tip of follow.',
    elevation: 'Cue elevated 20–30 degrees — not vertical.',
    speed: 'soft',
    speedDetail: 'Soft so curve has time before contact.',
    bridge: 'Short elevated bridge; careful balance.',
    steps: [
      'Elevate the cue 20–30°.',
      'Hit the high-right quadrant; stroke down the elevated line.',
      'The CB arcs around the 8, then straightens into the 1.',
    ],
    tips: ['This is swerve, not circus massé. Start at 20° elevation.'],
    commonMistakes: ['90° elevation and jumping the table.'],
    successLooksLike: 'The CB bends past the 8 and still pockets the 1.',
  },
  {
    id: 'sotd-15',
    name: 'Jump Over the Troublemaker',
    tagline: 'Controlled jump shot — legal elevation',
    what: 'Jump the cue ball over a blocking ball, land it, and pot the ball just beyond into the corner.',
    why: 'Teaches a short, legal jump for when a ball sits right in your line.',
    difficulty: 'Hard',
    category: 'jump',
    table: 'Short jump over the 7',
    setup: [
      '1-ball: 1.5 diamonds from the foot-right corner, straight in to it.',
      'Cue ball: 18 inches from the 1, straight behind it.',
      '7-ball: halfway between the cue ball and the 1, blocking the line.',
      'Use a jump cue if you have one; otherwise a playing cue elevated 45° or more, with care.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center of CB, elevated stick 45°+.',
    english: 'None.',
    elevation: '45–60 degrees.',
    speed: 'firm',
    speedDetail: 'Short firm dart stroke — not a swing from the shoulder.',
    bridge: 'Dart grip / short bridge above the ball.',
    steps: [
      'Chalk, elevate, aim center.',
      'Dart the tip into the top of the CB with a quick punch.',
      'The CB flies straight over the 7 and lands before the 1.',
    ],
    tips: ['Practice jump height on empty table first — protect cloth.'],
    commonMistakes: ['Scoop foul (hitting below center with elevation). Always hit down into the ball.'],
    successLooksLike: 'The CB clears the 7 cleanly, lands, and pots the 1 in the foot-right corner.',
  },
  {
    id: 'sotd-16',
    name: 'Massé Orbit (Training Version)',
    tagline: 'Steep elevation curve for advanced players only',
    what: 'Use a steep, low-right hit to bend the cue ball in a tight curve around the 5 into the 1, potting it in the right side pocket.',
    why: 'Introduces massé spin for advanced escapes (practice on old cloth).',
    difficulty: 'Insane',
    category: 'masse',
    table: 'Cue ball 4 inches off the right long rail; the 5 blocks the line to the 1',
    setup: [
      '1-ball: 5 inches from the right side pocket, 3.7 inches from the right long rail.',
      'Cue ball: 4 inches from the right long rail, 1.1 diamonds from the 1.',
      '5-ball: halfway between the cue ball and the 1, blocking the direct line.',
      'Clearance: room to raise the cue to 80° with no light fixture within 2 feet above.',
    ],
    objectBall: '1-ball',
    pocket: 'Right side pocket — pot the 1 once the curve is reliable',
    tipZone: '4:30-low-right',
    tipDetail: 'Low-right hit with a steep cue — extreme friction spin.',
    english: 'Heavy right side plus a draw component.',
    elevation: '60–80 degrees. Cloth risk: use old cloth / careful practice.',
    speed: 'soft',
    speedDetail: 'Soft punch — massé is spin, not power.',
    bridge: 'Mechanical or very stable elevated bridge.',
    steps: [
      'Only attempt if your room allows elevated cues safely.',
      'Steep cue, low-side tip, short stroke.',
      'Watch CB path curve dramatically.',
    ],
    tips: ['Film from above. Celebrate path, not just pocket.'],
    commonMistakes: ['Ripping the cloth — if unsure, skip and do swerve (sotd-14) instead.'],
    successLooksLike: 'The CB takes a banana path around the 5 into the 1.',
  },
  {
    id: 'sotd-17',
    name: 'Rail-First Kick Safety',
    tagline: 'Not a pot — a pro safety that wins frames',
    what: 'Kick off the right long rail to thin the 8 when the 3 blocks the direct hit, and leave the cue ball safe.',
    why: 'Teaches a kick safety that gets you out of a snooker legally and leaves your opponent little.',
    difficulty: 'Medium',
    category: 'kick',
    table: 'Snookered on the 8 by the 3',
    setup: [
      '8-ball: 2.4 diamonds from the foot rail, 1.7 diamonds from the left long rail.',
      '3-ball: halfway between the cue ball and the 8, blocking the direct hit.',
      'Cue ball: 1.4 diamonds from the head rail, 2 diamonds from the left long rail.',
      'Route: CB → right long rail → 8-ball.',
    ],
    objectBall: '8-ball (thin touch)',
    pocket: 'None — legal thin contact and a safe leave',
    tipZone: 'center',
    tipDetail: 'Center for predictable first rail.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft so the thin touch doesn’t sell out.',
    bridge: 'Long.',
    steps: [
      'Pick a right-long-rail contact that guarantees a thin hit on the 8.',
      'Prefer a thin contact that leaves the CB tight to the 8.',
      'Execute a soft center-ball kick.',
    ],
    tips: ['In race formats, this shot wins more matches than trick pots.'],
    commonMistakes: ['Blasting into a double-kiss sellout.'],
    successLooksLike: 'Legal hit; opponent is left tough or hooked.',
  },
  {
    id: 'sotd-18',
    name: 'Frozen Combo Rail Run',
    tagline: 'Two balls frozen on the rail — precision cut',
    what: 'Hit the 1, frozen to the 2 on the left long rail, so the 2 slides down the rail into the foot-left corner.',
    why: 'Teaches how frozen balls pass the hit along the line of centers.',
    difficulty: 'Hard',
    category: 'combo',
    table: 'Two balls frozen together on the left long rail',
    setup: [
      '2-ball: frozen to the left long rail, one diamond from the foot-left corner.',
      '1-ball: frozen to the 2, 1.5 inches from the left long rail.',
      'Cue ball: 1.3 diamonds from the 1, with a ¾ hit on the 1.',
      'Route: CB → 1-ball → 2-ball → foot-left corner.',
    ],
    objectBall: '1-ball into the 2-ball',
    pocket: 'Foot-left corner (for the 2)',
    tipZone: 'center',
    tipDetail: 'Center; frozen combos hate spin.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium.',
    bridge: 'Stable.',
    steps: [
      'Line the contact through the 1 into the 2 along the rail line.',
      'Hit the 1 so it transfers cleanly; avoid heavy throw.',
    ],
    tips: ['If the 2 freezes and dies, you need a fuller hit on the 1.'],
    commonMistakes: ['English for no reason.'],
    successLooksLike: 'The 2 slides along the rail into the foot-left corner.',
  },
  {
    id: 'sotd-19',
    name: 'Wing Shot Bank',
    tagline: 'Flying cut-bank hybrid for shape',
    what: 'Cut the 1 into the right long rail so it banks across and up the table into the head-left corner.',
    why: 'Teaches you to combine a cut angle and a bank angle in one shot.',
    difficulty: 'Hard',
    category: 'bank',
    table: '1-ball one diamond off the right long rail; cut-bank to the head-left corner',
    setup: [
      '1-ball: one diamond from the right long rail, 2.5 diamonds from the foot rail.',
      'Cue ball: 1.75 diamonds from the 1, set for a 35° cut that drives the 1 into the right long rail.',
      'Route: 1-ball → right long rail → head-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Head-left corner, banked off the right long rail',
    tipZone: 'center',
    tipDetail: 'Center ball.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium firm.',
    bridge: 'Open.',
    steps: [
      'See cut angle into the rail, then bank angle out.',
      'Commit to a single contact point on the cushion.',
      'Smooth stroke; stay down.',
    ],
    tips: ['Call the rail contact out loud — forces specificity.'],
    commonMistakes: ['Mixing cut and bank guesses mid-stroke.'],
    successLooksLike: 'The 1 hits the called diamond on the right long rail and tracks to the head-left corner.',
  },
  {
    id: 'sotd-20',
    name: 'Length of the Table Stop',
    tagline: 'Stun from distance — timing the slide',
    what: 'Pot a long straight ball so the cue ball arrives sliding and stops at contact.',
    why: 'Teaches stop-shot speed control from long range.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Cue ball at the head string, 1-ball on the foot string',
    setup: [
      '1-ball: on the foot string, one diamond from the left long rail, straight in to the foot-left corner.',
      'Cue ball: 2 inches past the head string, straight behind the 1.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: 'center',
    tipDetail: 'Center; speed creates slide that dies into stun at impact.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — calibrated so CB is still sliding at contact.',
    bridge: 'Long open.',
    steps: [
      'Center aim, medium stroke.',
      'If the CB rolls forward after contact, hit firmer or half a tip lower.',
      'If the CB draws back, you hit below center: return to center.',
    ],
    tips: ['Distance stun is a feel skill — log speeds that work on your cloth.'],
    commonMistakes: ['Copying bar-table speed on a fast 9-footer.'],
    successLooksLike: 'Long pot; the CB stops within 3 inches of the contact point.',
  },
  {
    id: 'sotd-21',
    name: 'Reverse English Bank',
    tagline: 'Kill the rail rebound for a short bank',
    what: 'Bank the 1 off the left long rail with reverse english so it comes off shorter and drops in the head-right corner.',
    why: 'Shows how spin changes a bank so you can fix banks that run long.',
    difficulty: 'Insane',
    category: 'bank',
    table: 'Short cross-bank to the head-right corner',
    setup: [
      '1-ball: 10 inches from the left long rail, 2.7 diamonds from the head rail.',
      'Cue ball: 1.2 diamonds from the 1, straight in behind it.',
      'Route: 1-ball → left long rail → head-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Head-right corner, banked off the left long rail',
    tipZone: '9-left',
    tipDetail: 'Reverse english (left, 9 o’clock, half a tip) against the bank direction to shorten the rebound.',
    english: 'Reverse / check english.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium; reverse bites better without blasting.',
    bridge: 'Closed.',
    steps: [
      'Identify natural bank (too long).',
      'Apply reverse english and aim for a shorter rail path.',
      'Soft delivery so spin lives until the rail.',
    ],
    tips: ['Master center banks before reverse banks.'],
    commonMistakes: ['Overspin miscue on the side of the CB.'],
    successLooksLike: 'A bank that would run long comes off short and drops in the head-right corner.',
  },
  {
    id: 'sotd-22',
    name: 'Ticket Pocket Thin Kick',
    tagline: 'One-rail kick to nick a hanger into the right side pocket',
    what: 'Kick off the left long rail and thin-nick the 1 hanging in the right side pocket, with the 5 blocking the direct hit.',
    why: 'Teaches soft, accurate kicks at hangers without a double kiss.',
    difficulty: 'Hard',
    category: 'kick',
    table: '1-ball hanging in the right side pocket; the 5 blocks the direct line',
    setup: [
      '1-ball: 4 inches from the right side pocket, 2.6 inches from the right long rail.',
      'Cue ball: 1.6 diamonds from the head rail, 1.1 diamonds from the right long rail.',
      '5-ball: halfway between the cue ball and the 1, blocking the direct hit.',
      'Route: CB → left long rail → 1-ball → right side pocket.',
    ],
    objectBall: '1-ball (hanger)',
    pocket: 'Right side pocket',
    tipZone: 'center',
    tipDetail: 'Center first.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — hangers die if overhit after kick.',
    bridge: 'Long.',
    steps: [
      'Plan a left-long-rail contact that gives a thin nick on the 1.',
      'Soft kick; don’t double-kiss.',
    ],
    tips: ['Kick thin: a full hit on a hanger at the jaw can double-kiss it out.'],
    commonMistakes: ['Hero blast that rattles the side.'],
    successLooksLike: 'Gentle kick-nick; the 1 drops in the right side pocket.',
  },
  {
    id: 'sotd-23',
    name: 'Stack Split with Soft Stun',
    tagline: 'Open a cluster without moving the world',
    what: 'Stun the cue ball into the front ball of a small cluster so the two back balls spread apart.',
    why: 'Teaches you to open a cluster gently without scattering the table.',
    difficulty: 'Medium',
    category: 'position',
    table: 'Three-ball cluster on the long string',
    setup: [
      '1-ball: on the long string, 6 inches past the center string.',
      '2-ball: frozen to the 1, on its foot side.',
      '3-ball: frozen to the 1 and to the 2.',
      'Cue ball: on the long string, 1.3 diamonds from the 1.',
    ],
    objectBall: '1-ball (front of the cluster)',
    pocket: 'None — the goal is a controlled split',
    tipZone: 'center',
    tipDetail: 'Stun center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft stun — energy transfers without explosion.',
    bridge: 'Open.',
    steps: [
      'Identify the key ball whose contact opens lanes (here the 1).',
      'Soft center hit; watch the 2 and 3 open.',
    ],
    tips: ['In real matches, sometimes leave the cluster and play safe instead.'],
    commonMistakes: ['Power splits that sell out both balls to opponent.'],
    successLooksLike: 'The 2 and 3 split apart and stop within 1.5 diamonds of the center spot; the CB stops within 4 inches of the contact point.',
  },
  {
    id: 'sotd-24',
    name: 'Behind-the-Back Novelty (Rail Assist)',
    tagline: 'Party trick: one-handed rail bridge — control first',
    what: 'Pot a dead-straight short ball into the foot-right corner with a behind-the-back stroke, bridging on the rail.',
    why: 'A fun novelty that still trains a smooth, straight stroke.',
    difficulty: 'Medium',
    category: 'novelty',
    table: 'Short straight pot along the right long rail',
    setup: [
      '1-ball: 6 inches from the foot-right corner, 1.4 inches from the right long rail.',
      'Cue ball: 8.4 inches from the 1, straight behind it along the rail, with a 6.2-inch gap to the 1.',
      'Stance: cue behind your back, bridge hand flat on the rail; only with space behind you.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center — novelty is hard enough.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft.',
    bridge: 'Rail bridge (hand flat on the rail).',
    steps: [
      'Clear the area: no players, chairs or lights within a cue length behind you.',
      'Practice the stroke one-handed from the rail first; soft center stroke.',
      'Switch to behind-the-back after 8 makes in 10.',
    ],
    tips: ['Film it. RackUp highlight reel fuel.'],
    commonMistakes: ['Trying behind-the-back before you can pot it one-handed from the rail.'],
    successLooksLike: 'The 1 drops; you look ridiculous in the best way.',
  },
  {
    id: 'sotd-25',
    name: 'Double Kiss Escape',
    tagline: 'Use the kiss on purpose when frozen',
    what: 'Thin-cut a rail-frozen ball when your cue ball sits 0.4 inch from it, so the balls don’t double-kiss.',
    why: 'Teaches you how to free a frozen ball without a kiss or a scratch.',
    difficulty: 'Hard',
    category: 'carom',
    table: 'Cue ball 0.4 inch from the 1, both on the right long rail',
    setup: [
      '1-ball: frozen to the right long rail, 1.6 diamonds from the foot rail.',
      'Cue ball: 2 inches from the right long rail, with a 0.4-inch gap to the 1.',
      'A full hit would double-kiss; cut the 1 thin, down the rail into the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '1:30-high-right',
    tipDetail: 'A quarter tip high-right to change the kiss geometry.',
    english: 'A quarter tip of right side.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — log which speeds free the 1 on your cloth.',
    bridge: 'Short.',
    steps: [
      'Hit thin enough that the CB leaves the 1’s line before the 1 comes back off the rail.',
      'Log which tip zones free the ball on your cloth.',
    ],
    tips: ['Frozen balls are physics puzzles — patience > ego.'],
    commonMistakes: ['Blasting frozen balls and scratching.'],
    successLooksLike: 'The 1 runs down the rail into the foot-right corner with no double kiss and no scratch.',
  },
  {
    id: 'sotd-26',
    name: 'Side-Pocket Soft Cut',
    tagline: 'The underrated money cut',
    what: 'Softly cut the 1 into the right side pocket at a 38° angle.',
    why: 'Builds the soft speed side pockets need so the ball doesn’t rattle out.',
    difficulty: 'Medium',
    category: 'position',
    table: '1-ball one diamond out from the right side pocket',
    setup: [
      '1-ball: one diamond from the right side pocket, one diamond from the right long rail.',
      'Cue ball: 1.6 diamonds from the 1, set for a 38° cut into the right side pocket.',
    ],
    objectBall: '1-ball',
    pocket: 'Right side pocket',
    tipZone: 'center',
    tipDetail: 'Center tip; side pockets punish spin.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — sides rattle when overhit.',
    bridge: 'Open.',
    steps: [
      'Ghost ball aim for the side mouth center, not the back of the pocket.',
      'Soft center stroke; stay down.',
    ],
    tips: ['On fast cloth, aim 1 inch deeper into the pocket.'],
    commonMistakes: [
      'Power cutting sides — highest rattle rate in pool.',
    ],
    successLooksLike: 'The 1 drops in the center of the right side pocket, no rattle.',
  },
  {
    id: 'sotd-27',
    name: 'Lengthwise Bank Cross-Corner',
    tagline: 'Big table bank for diamond students',
    what: 'Bank the 1 from the center spot off the right long rail into the foot-left corner.',
    why: 'Practice for long banks with a diamond system and one steady speed.',
    difficulty: 'Hard',
    category: 'bank',
    table: '1-ball on the center spot, bank to the foot-left corner',
    setup: [
      '1-ball: on the center spot.',
      'Cue ball: 1.3 diamonds from the 1, straight in behind it toward the right long rail.',
      'Route: 1-ball → right long rail → foot-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner, banked off the right long rail',
    tipZone: 'center',
    tipDetail: 'Center ball.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm bank speed.',
    bridge: 'Closed.',
    steps: [
      'Use corner-5 or equal-distance system for long banks.',
      'Commit to rail contact; stroke firm center.',
    ],
    tips: ['Banks are 50% speed discipline — pick one speed for a practice block.'],
    commonMistakes: ['Changing speed every attempt with the same aim.'],
    successLooksLike: 'The 1 hits the planned diamond and tracks into the foot-left corner.',
  },
  {
    id: 'sotd-28',
    name: 'Soft Safety: Hide Behind the 8',
    tagline: 'Legal hit + CB death behind the money ball',
    what: 'Barely touch the 3 and let the cue ball die against the 8 on the center spot.',
    why: 'Teaches a simple safety that hides the cue ball behind the 8.',
    difficulty: 'Medium',
    category: 'position',
    table: 'Open-table safety around the 8',
    setup: [
      '8-ball: on the center spot.',
      '3-ball: 12 inches past the center string, 18 inches from the left long rail.',
      'Cue ball: 1.4 diamonds from the 3, set for a 61° cut (a thin hit).',
      'Goal: thin the 3, then stop the CB behind the 8.',
    ],
    objectBall: '3-ball (thin)',
    pocket: 'None — a safety',
    tipZone: 'center',
    tipDetail: 'Center, soft.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather touch.',
    bridge: 'Soft grip pressure.',
    steps: [
      'Plan a thin contact that moves the 3 under a diamond.',
      'The CB path should end behind the 8.',
      'Execute the softest legal stroke you can control.',
    ],
    tips: ['Great league shot — earns more racks than trick shots.'],
    commonMistakes: ['Moving the 3 too far and leaving an easy shot.'],
    successLooksLike: 'The 3 moves under a diamond; the CB stops within an inch of the 8, leaving your opponent hooked.',
  },
  {
    id: 'sotd-29',
    name: 'Elevated Draw Over a Rail Nip',
    tagline: '10° elevation + low tip when the rail crowds you',
    what: 'Draw the cue ball off the rail with the cue raised 10° when it sits 2.7 inches from the cushion.',
    why: 'Teaches you to draw cleanly when the rail cramps your bridge.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Cue ball 2.7 inches from the right long rail, needs draw',
    setup: [
      '1-ball: 1.1 diamonds from the foot-right corner, 2.4 inches from the right long rail.',
      'Cue ball: 2.7 inches from the right long rail, 1.8 diamonds from the 1; 10° cut into the foot-right corner.',
      'The low bridge is cramped by the rail — raise the cue 10°.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '6-low',
    tipDetail: 'Low tip with the cue raised 10°.',
    english: 'None.',
    elevation: '10–20 degrees to clear the rail.',
    speed: 'soft',
    speedDetail: 'Soft–medium draw.',
    bridge: 'Rail bridge elevated.',
    steps: [
      'Rail bridge; raise the cue 10°, no more.',
      'Low tip, soft stroke, stay still at impact.',
    ],
    tips: ['Mechanical bridge is legal and smart — ego freezes more balls than bridges do.'],
    commonMistakes: ['Over-elevating and scooping.'],
    successLooksLike: 'The 1 drops; the CB draws back and away from the rail.',
  },
  {
    id: 'sotd-30',
    name: 'Clockwise Curve Drag',
    tagline: 'High-right roll that bends late',
    what: 'Use high-right spin so the cue ball bends right late, around the 8, and pots the 1 on a 9° cut.',
    why: 'Teaches a soft curve for getting around a ball that’s barely in the way.',
    difficulty: 'Medium',
    category: 'curve',
    table: 'Long shot with a late right bend',
    setup: [
      '1-ball: 0.7 diamonds from the foot rail, 0.7 diamonds from the right long rail.',
      '8-ball: halfway between the cue ball and the 1, on the direct line, blocking a direct hit.',
      'Cue ball: on the long string, 5 inches toward the head from the center string; 9° cut into the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '1:30-high-right',
    tipDetail: 'High-right quadrant, half a tip off each axis.',
    english: 'Right plus roll.',
    elevation: 'Level to 10°.',
    speed: 'soft',
    speedDetail: 'Soft so curve develops.',
    bridge: 'Open.',
    steps: [
      'Aim 2 inches left of the plain line; the spin brings the CB back right.',
      'Soft high-right stroke.',
    ],
    tips: ['Mark the CB start and end with chalk dots on the rail cap for feedback.'],
    commonMistakes: ['Firm speed that kills curve.'],
    successLooksLike: 'A visible late right bend around the 8 into the 1.',
  },
  {
    id: 'sotd-31',
    name: 'Three-Ball Line Combo',
    tagline: 'Centers stacked like a runway',
    what: 'Shoot the 1 into a straight line of three so the 3 drops in the foot-left corner.',
    why: 'Teaches setup and a soft stroke for multi-ball combos.',
    difficulty: 'Medium',
    category: 'combo',
    table: 'Three balls in a line to the foot-left corner',
    setup: [
      '3-ball: 1.3 diamonds from the foot-left corner.',
      '2-ball: 11 inches from the 3, on the line from the 3 back toward the center of the table.',
      '1-ball: 11 inches from the 2, on the same line.',
      'Cue ball: one diamond from the 1, on the line extended.',
      'Route: CB → 1-ball → 2-ball → 3-ball → foot-left corner.',
    ],
    objectBall: '1-ball → 2-ball → 3-ball',
    pocket: 'Foot-left corner (for the 3)',
    tipZone: 'center',
    tipDetail: 'Center stun.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft — multi-ball combos amplify error with speed.',
    bridge: 'Open.',
    steps: [
      'Align all centers with one eye closed for a second — check the line.',
      'Soft center hit on the 1.',
    ],
    tips: ['If the 3 misses left, the whole line was rotated — fix the setup, not the stroke.'],
    commonMistakes: ['Hitting hard “to make sure.”'],
    successLooksLike: 'Domino transfer; the 3 drops.',
  },
  {
    id: 'sotd-32',
    name: 'Jump-Cut Over the 5',
    tagline: 'Jump a ball and still cut the 1 in',
    what: 'Jump the cue ball over the 5, land, and cut the 1 30° into the foot-right corner.',
    why: 'Teaches aiming a cut shot through a jump, the most common real jump situation.',
    difficulty: 'Hard',
    category: 'jump',
    table: 'Jump over the 5 into a 30° cut',
    setup: [
      '1-ball: one diamond from the foot rail, 1.5 diamonds from the right long rail.',
      'Cue ball: 22 inches from the 1, set for a 30° cut into the foot-right corner.',
      '5-ball: 9 inches from the cue ball, on the cue ball’s line to the ghost ball, blocking the cut.',
      'Use a jump cue; the cue ball flies straight over the 5 and lands 7 inches before the ghost ball.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center of the cue ball; the jump cue strikes down at 50°.',
    english: 'None.',
    elevation: '45–60° with a jump cue.',
    speed: 'firm',
    speedDetail: 'Short firm dart stroke — not a swing from the shoulder.',
    bridge: 'Dart grip / short bridge above the ball.',
    steps: [
      'Aim the cut first: pick the ghost-ball spot for 30°.',
      'Elevate along that aim line and dart down into the center of the CB.',
      'The CB clears the 5, lands, rolls into the ghost-ball spot and cuts the 1 in.',
    ],
    tips: ['Check your aim line from behind the CB before you raise the cue; elevation hides the ghost ball.'],
    commonMistakes: ['Scoop foul (hitting below center with elevation). Always hit down into the ball.', 'Changing the aim while raising the cue.'],
    successLooksLike: 'The CB clears the 5, lands, and cuts the 1 into the foot-right corner.',
  },
  {
    id: 'sotd-33',
    name: 'Hold-Up English Along the Rail',
    tagline: 'Slide the CB up-table with reverse after a rail first',
    what: 'Go off the left long rail into the 1 with low reverse english so the cue ball holds up-table after the pot.',
    why: 'Teaches you to kill cue-ball speed off a rail for better position.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Rail-first natural into the right side pocket',
    setup: [
      '1-ball: 8 inches from the right side pocket, 6 inches from the right long rail.',
      'Cue ball: 1.4 diamonds from the head rail, 1.6 diamonds from the left long rail.',
      'Route: CB → left long rail → 1-ball → right side pocket.',
      'The CB must hold up-table instead of racing toward the foot.',
    ],
    objectBall: '1-ball',
    pocket: 'Right side pocket',
    tipZone: '7:30-low-left',
    tipDetail: 'Low-left (7:30), half a tip low and half a tip left: reverse off the left long rail.',
    english: 'Hold-up / reverse relative to the CB’s travel off the rail.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium.',
    bridge: 'Closed.',
    steps: [
      'Pocket the natural with planned reverse.',
      'Watch the CB stop short instead of running toward the foot.',
    ],
    tips: ['Map both sides of the table; the reverse side flips with direction.'],
    commonMistakes: ['Too much reverse → miscue or missed natural.'],
    successLooksLike: 'The 1 drops; the CB stops up-table, short of the right side pocket.',
  },
  {
    id: 'sotd-34',
    name: 'Dead Ball Bank (Soft)',
    tagline: 'Bank that dies in the pocket without rattle',
    what: 'Softly bank the 1 off the right long rail across into the left side pocket so it dies in the hole.',
    why: 'Teaches soft speed on side banks so they drop instead of rattling.',
    difficulty: 'Medium',
    category: 'bank',
    table: 'Cross-side bank to the left side pocket',
    setup: [
      '1-ball: 4 inches from the right long rail, 1.4 diamonds from the right side pocket.',
      'Cue ball: 1.4 diamonds from the 1, with a full hit available.',
      'Route: 1-ball → right long rail → left side pocket.',
    ],
    objectBall: '1-ball',
    pocket: 'Left side pocket, banked off the right long rail',
    tipZone: 'center',
    tipDetail: 'Center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Softer than you think: the 1 should reach the pocket with under a diamond of roll left.',
    bridge: 'Open.',
    steps: [
      'Aim bank line.',
      'Soft center hit — let the pocket catch it.',
    ],
    tips: ['Side pockets are shallow; soft is your friend.'],
    commonMistakes: ['Firm bank that flies past the mouth.'],
    successLooksLike: 'A quiet drop in the left side pocket — no rattle.',
  },
  {
    id: 'sotd-35',
    name: 'Point-to-Point Long Pot',
    tagline: 'Diamond to diamond straight aim training',
    what: 'Pot a long straight ball from a head-string diamond line to a foot-string diamond line.',
    why: 'Builds a repeatable pre-shot routine and straight aim.',
    difficulty: 'Easy',
    category: 'position',
    table: '1-ball on a foot-string diamond line, cue ball on a head-string diamond line',
    setup: [
      '1-ball: on the foot string, one diamond from the left long rail.',
      'Cue ball: on the head string, one diamond from the right long rail, straight in through the 1 to the foot-left corner.',
      'No english today — purity only.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: 'center',
    tipDetail: 'Dead center.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium consistent.',
    bridge: 'Your match bridge.',
    steps: [
      'Pre-shot routine: stand, aim, down, feather, go.',
      'Center tip every rep.',
      'Make 7/10 before leaving the drill.',
    ],
    tips: ['This is the foundation under every trick shot on this list.'],
    commonMistakes: ['Skipping routine on “easy” long pots.'],
    successLooksLike: 'Boring, repeatable long pots — the real flex.',
  },
  {
    id: 'sotd-36',
    name: 'One-Rail Kick Past a Blocker',
    tagline: 'Kick off one rail when a ball sits dead on your line',
    what: 'With the 7 dead on your line, kick off the right long rail into the 1 and send it into the foot-left corner.',
    why: 'Gives you a reliable one-rail kick system for the most common snooker.',
    difficulty: 'Hard',
    category: 'kick',
    table: 'The 7 blocks the middle of the table',
    setup: [
      '1-ball: 1.4 diamonds from the foot-left corner, 10 inches from the left long rail.',
      'Cue ball: 1.6 diamonds from the head rail, 2 diamonds from the right long rail.',
      '7-ball: halfway between the cue ball and the 1, dead on the line.',
      'Route: CB → right long rail → 1-ball → foot-left corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner',
    tipZone: 'center',
    tipDetail: 'Center ball.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm, so the kick angle holds.',
    bridge: 'Long bridge, stable.',
    steps: [
      'Mirror the 1 across the right long rail to find the aim point on the rail.',
      'Take 5 kicks with that aim and note where the CB meets the 1.',
      'Move the rail aim point 1 inch at a time until the 1 drops.',
    ],
    tips: ['A mirror-aimed one-rail kick beats guesswork; pros take the higher-percentage escape.'],
    commonMistakes: ['Changing plan mid-stroke.'],
    successLooksLike: 'The CB comes off the right long rail, hits the 1, and the 1 drops in the foot-left corner.',
  },
  {
    id: 'sotd-37',
    name: 'Spin-to-Win Rail First',
    tagline: 'Running english stretches a rail-first natural',
    what: 'Go off the left long rail with running english so the cue ball comes off wider and pots the 1 in the right side pocket.',
    why: 'Shows how running english widens a rebound angle.',
    difficulty: 'Hard',
    category: 'curve',
    table: 'Rail-first natural into the right side pocket',
    setup: [
      '1-ball: 1.4 diamonds from the right side pocket, 16 inches from the right long rail.',
      'Cue ball: 1.8 diamonds from the head rail, 14 inches from the right long rail.',
      'Route: CB → left long rail → 1-ball → right side pocket.',
      'Running english widens the angle off the left long rail.',
    ],
    objectBall: '1-ball',
    pocket: 'Right side pocket',
    tipZone: '3-right',
    tipDetail: 'Running english: tip in the direction that accelerates along the rail after contact.',
    english: 'Running (forward along the rail path).',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium.',
    bridge: 'Closed.',
    steps: [
      'Identify running side for your CB path.',
      'Half tip running, medium stroke into the rail first.',
      'Collect the natural.',
    ],
    tips: ['If the angle widens too much, reduce english before changing aim.'],
    commonMistakes: ['Confusing reverse and running — sketch the CB path on paper first.'],
    successLooksLike: 'Rail-first natural that wouldn’t exist with center ball.',
  },
  {
    id: 'sotd-38',
    name: 'The Spotlight 8 Cut',
    tagline: 'Pressure cut: pretend it’s hill-hill',
    what: 'Make a 40° cut on the 8 into the corner with one stroke, as if the match is on the line.',
    why: 'Practices trusting your routine on a must-make shot.',
    difficulty: 'Medium',
    category: 'position',
    table: '8 between the center spot and the foot spot, 40° cut',
    setup: [
      '8-ball: 12 inches past the center string, 2 inches from the long string toward the left long rail.',
      'Cue ball: 1.6 diamonds from the 8, set for a 40° cut into the foot-left corner.',
      'Pressure rule: one stroke attempt, then reset (simulates match nerves).',
    ],
    objectBall: '8-ball',
    pocket: 'Foot-left corner',
    tipZone: 'center',
    tipDetail: 'Center under pressure — simplify.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'soft',
    speedDetail: 'Soft–medium pocket speed.',
    bridge: 'Match routine.',
    steps: [
      'Full routine. No rushed downs.',
      'Ghost ball aim.',
      'One intentional stroke. Win or reset — no “fix” babying.',
    ],
    tips: ['Breathe out on the stroke. Heart rate is a real variable.'],
    commonMistakes: ['Second-guessing mid-down.'],
    successLooksLike: '8 drops; you walk like it was always easy.',
  },
  {
    id: 'sotd-39',
    name: 'Quad Rail Dream (Path Only)',
    tagline: 'Four-rail CB path for shape geeks — no object ball',
    what: 'Send the cue ball around four rails, every contact on a diamond, and stop it on the foot spot, with no object ball.',
    why: 'Builds kick and position sense by calling each rail contact.',
    difficulty: 'Insane',
    category: 'kick',
    table: 'Open table; cue ball only',
    setup: [
      'Cue ball: 3 diamonds from the head rail, half a diamond from the left long rail.',
      'Route: CB → left long rail → head rail → right long rail → foot rail.',
      'Contacts: left long rail 2 diamonds from the head rail; head rail 1 diamond from the left long rail; right long rail 6 diamonds from the head rail; foot rail 1 diamond from the right long rail.',
      'Finish: within half a diamond of the foot spot.',
    ],
    objectBall: 'None (CB-only path shot)',
    pocket: 'None — the cue ball finishes on the foot spot',
    tipZone: '12-high',
    tipDetail: 'High center: one tip above center keeps the rails lively.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail.',
    bridge: 'Long.',
    steps: [
      'Call the four rail contacts in order.',
      'Execute; mark where the CB stops.',
      'Adjust the first-rail aim until the CB stops within half a diamond of the foot spot.',
    ],
    tips: ['This builds kick IQ faster than random kicking at balls.'],
    commonMistakes: ['Random blasting without named contacts.'],
    successLooksLike: 'The CB hits four rails on the called diamonds and stops within half a diamond of the foot spot.',
  },
  {
    id: 'sotd-40',
    name: 'Celebration Combo Off Two',
    tagline: 'End the cycle with a crowd-pleasing combo bank hybrid',
    what: 'Shoot the 1 into the 2 so the 2 banks off the right long rail into the foot-left corner.',
    why: 'Combines combo and bank aiming in one shot.',
    difficulty: 'Hard',
    category: 'combo',
    table: 'Combo into a bank',
    setup: [
      '2-ball: 1.6 diamonds from the right side pocket, 16 inches from the right long rail.',
      '1-ball: 14 inches from the 2.',
      'Cue ball: 14 inches from the 1, straight through the 1 into the 2.',
      'Route: CB → 1-ball → 2-ball → right long rail → foot-left corner.',
    ],
    objectBall: '1-ball into the 2-ball (bank)',
    pocket: 'Foot-left corner, after the 2 banks off the right long rail',
    tipZone: 'center',
    tipDetail: 'Center through the whole chain.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium — enough for the bank leg.',
    bridge: 'Closed.',
    steps: [
      'Set the 1–2 combo line for the 2’s bank angle.',
      'Soft–medium center hit on the 1.',
      'Watch the 2 take the right long rail to the corner.',
    ],
    tips: ['If the bank misses, keep the setup and move the 2 half an inch, not your stroke.'],
    commonMistakes: ['Too much speed on the combo transfer.'],
    successLooksLike: 'Combo-bank drops — save the clip for Memories.',
  },

  // ---------------------------------------------------------------------------
  // Artistic / exhibition-style shots (inspired by public show repertoires of
  // legends like Mike Massey & Florian "Venom" Kohler — originals for practice,
  // not licensed routines. Every diagram uses balls only; prioritize cloth safety.)
  // ---------------------------------------------------------------------------
  {
    id: 'sotd-41',
    name: 'Butterfly Spread',
    tagline: 'Massey-style wing: two outer balls fly to opposite corners',
    what: 'Hit the 1 full so its wing balls, the 2 and 3, fly into opposite foot corners.',
    why: 'A crowd-pleasing exhibition shot that rewards a perfectly centered hit.',
    difficulty: 'Hard',
    category: 'novelty',
    table: 'Three-ball butterfly on the foot spot',
    setup: [
      '1-ball: on the foot spot (the body).',
      '2-ball: 5.4 inches past the foot string, 1.7 inches from the long string on the left side.',
      '3-ball: 5.4 inches past the foot string, 1.7 inches from the long string on the right side.',
      'Cue ball: on the long string, behind the head string, straight into the 1.',
    ],
    objectBall: '1-ball (drives the 2 and 3)',
    pocket: 'Both foot corners: the 2 in the foot-left corner, the 3 in the foot-right corner',
    tipZone: 'center',
    tipDetail: 'Dead center for even energy left/right.',
    english: 'None. Any side spin biases one wing.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm, even stroke — both wings need similar pace.',
    bridge: 'Closed, locked.',
    steps: [
      'Square the wings so distances to each corner are equal.',
      'Hit the 1 full and square with center tip.',
      'Follow through straight; do not steer after contact.',
      'Watch the 2 and 3 race toward opposite corners.',
    ],
    tips: [
      'Start with the wings 4.5 inches past the foot string; widen as your make rate climbs.',
      'Film from the foot of the table — classic exhibition angle.',
    ],
    commonMistakes: [
      'Hitting left or right of center on the CB — one wing dies.',
      'Wings not mirrored — fix geometry before blaming stroke.',
    ],
    successLooksLike: 'The 2 drops in the foot-left corner and the 3 in the foot-right corner on the same stroke.',
  },
  {
    id: 'sotd-42',
    name: 'Machine-Gun Line',
    tagline: 'Venom energy: rip a straight line of balls in sequence',
    what: 'Shoot into a line of four balls with quarter-inch gaps so the 4 drops in the foot-left corner.',
    why: 'Teaches lining up long combos and smooth medium speed.',
    difficulty: 'Hard',
    category: 'combo',
    table: 'Four balls in a tight line to the foot-left corner',
    setup: [
      '4-ball: 1.1 diamonds from the foot-left corner.',
      '3-ball: 0.25-inch gap to the 4, on the line back from the 4.',
      '2-ball: 0.25-inch gap to the 3.',
      '1-ball: 0.25-inch gap to the 2.',
      'Cue ball: one diamond from the 1, on the line extended.',
      'Route: CB → 1-ball → 2-ball → 3-ball → 4-ball → foot-left corner.',
    ],
    objectBall: '1-ball → 2-ball → 3-ball → 4-ball',
    pocket: 'Foot-left corner (for the 4)',
    tipZone: 'center',
    tipDetail: 'Center stun so the chain does not throw offline.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium-firm — enough to carry the chain, not so hard it sprays.',
    bridge: 'Open, chin low.',
    steps: [
      'Sight the centers of all four balls as one runway into the pocket.',
      'Medium center hit on the 1.',
      'Hold still — the machine-gun is the rapid transfer sound.',
    ],
    tips: ['If the 4 misses left, the whole line was rotated — rebuild the setup.'],
    commonMistakes: ['Hero speed that throws the 4 offline.'],
    successLooksLike: 'Rapid-fire transfers; the 4 drops clean.',
  },
  {
    id: 'sotd-43',
    name: 'Squeeze Between Friends',
    tagline: 'Classic squeeze: CB threads a gap you “shouldn’t” fit',
    what: 'Feather the cue ball through the 3-inch gap between the 7 and 8 to pot the 1 behind them.',
    why: 'Trains a dead-straight stroke and fine speed control.',
    difficulty: 'Insane',
    category: 'novelty',
    table: 'Two blockers with a 3-inch gate',
    setup: [
      '1-ball: one diamond from the foot-left corner.',
      '8-ball: 3-inch gap to the 7, blocking one side of the line.',
      '7-ball: on the other side of the line, forming the gate with the 8; the cue ball fits through with room to spare.',
      'Cue ball: 4.2 diamonds from the 1, with a straight line through the center of the gate into the 1.',
    ],
    objectBall: '1-ball (beyond the gate)',
    pocket: 'Foot-left corner',
    tipZone: 'center',
    tipDetail: 'Center and soft — control over flair.',
    english: 'None on first successful reps.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather. Squeeze shots die when overhit.',
    bridge: 'Long, quiet.',
    steps: [
      'Pick the exact gap centerline.',
      'Feather the CB through the gate into the 1.',
      'Celebrate not touching the 7 or 8 more than the pot itself.',
    ],
    tips: ['Widen the gap until you make 5 in 10, then tighten in quarter-inch steps — exhibition builders do this.'],
    commonMistakes: ['Aiming the pot first instead of clearing the gate.'],
    successLooksLike: 'The CB slips through the gate and pots the 1 clean.',
  },
  {
    id: 'sotd-44',
    name: 'Around-the-World CB Tour',
    tagline: 'Exhibition path shot: three-rail CB tour into a hanger',
    what: 'Send the cue ball around three rails and softly pot the 1 hanging in the head-left corner.',
    why: 'Builds multi-rail kick and position sense by naming rail diamonds.',
    difficulty: 'Hard',
    category: 'kick',
    table: 'Open table: three-rail CB tour to a hanger',
    setup: [
      '1-ball: 4.6 inches from the head-left corner (hanging in the jaws).',
      'Cue ball: 1.6 diamonds from the head rail, 12 inches from the right long rail.',
      'Route: CB → left long rail → foot rail → right long rail → 1-ball → head-left corner.',
      'The CB passes within half a diamond of the head spot on its way to the 1.',
    ],
    objectBall: '1-ball (hanger)',
    pocket: 'Head-left corner',
    tipZone: '12-high',
    tipDetail: 'High center, half a tip above center, to keep the cushions lively.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'firm',
    speedDetail: 'Firm multi-rail pace.',
    bridge: 'Long.',
    steps: [
      'Name each rail diamond before you shoot.',
      'Firm high-center stroke into the left long rail.',
      'Track the tour; adjust only the first-rail aim between reps.',
    ],
    tips: ['Massey exhibitions sell the path — call it out loud for the camera.'],
    commonMistakes: ['Random power without named diamonds.'],
    successLooksLike: 'The CB hits every called rail and pots the 1 in the head-left corner.',
  },
  {
    id: 'sotd-45',
    name: 'Elevator Jump Over Two Balls',
    tagline: 'A longer, higher hop over two frozen balls',
    what: 'Jump the cue ball over the 5 and 6, frozen together on your line, and pot the 1 straight into the foot-right corner.',
    why: 'Builds jump height and distance control when a one-ball hop is not enough.',
    difficulty: 'Insane',
    category: 'jump',
    table: 'Jump over two frozen balls',
    setup: [
      '1-ball: 1.3 diamonds from the foot-right corner, straight in to it.',
      'Cue ball: 22 inches from the 1, straight behind it.',
      '5-ball: 9 inches from the cue ball, on the line to the 1.',
      '6-ball: frozen to the 5, on the same line, so the hop must clear both balls.',
      'Use a jump cue: the cue ball takes off 4 inches before the 5 and flies straight to a landing 4 inches past the 6.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center of the CB, strike down.',
    english: 'None.',
    elevation: '50–60° with a jump cue (higher than a one-ball hop).',
    speed: 'firm',
    speedDetail: 'Short firm dart — height comes from elevation and acceleration, not body heave.',
    bridge: 'Dart grip above the ball.',
    steps: [
      'Clear the area; protect the cloth and lights.',
      'Dart into the top of the CB; the hop must clear both the 5 and the 6.',
      'Land 4 inches past the 6 and roll into the 1 without scooping.',
    ],
    tips: ['Master the one-ball hop (sotd-15) first, then add the 6.'],
    commonMistakes: ['Scoop foul. Always hit down into the ball.', 'Clipping the 6: raise the cue 5°, do not add speed.'],
    successLooksLike: 'The CB clears the 5 and 6, lands, and pots the 1 in the foot-right corner.',
  },
  {
    id: 'sotd-46',
    name: 'Two-Rail Cross Bank',
    tagline: 'Bank the 1 across the table twice into the foot corner',
    what: 'Bank the 1 off the right long rail, across to the left long rail, and into the foot-right corner.',
    why: 'Trains speed and angle control on two-rail object-ball banks.',
    difficulty: 'Hard',
    category: 'bank',
    table: '1-ball half a diamond off the right long rail; two-rail bank to the foot-right corner',
    setup: [
      '1-ball: 3 diamonds from the head rail, half a diamond from the right long rail.',
      'Cue ball: 1.4 diamonds from the 1, straight in behind it toward the right long rail.',
      'Route: 1-ball → right long rail → left long rail → foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner, after the right and left long rails',
    tipZone: 'center',
    tipDetail: 'Center ball for a predictable first rail.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium: the 1 should reach the foot-right corner with half a diamond of roll left.',
    bridge: 'Open.',
    steps: [
      'Plan both rail contacts: mirror the corner across the left long rail, then across the right long rail.',
      'Medium center hit, straight into the 1.',
      'If the 1 meets the left long rail short of your mark, move the cue ball half an inch to fix the first-rail angle.',
    ],
    tips: ['Bank angles change with speed: fix one speed for a practice block, then adjust aim.'],
    commonMistakes: ['Changing speed between attempts with the same aim.'],
    successLooksLike: 'The 1 hits the right long rail, then the left long rail, and drops in the foot-right corner.',
  },
  {
    id: 'sotd-47',
    name: 'Coin Marker Freeze',
    tagline: 'Massey-style precision: stop the 1 dead on a marker',
    what: 'Stun the 1 so it stops on a flat marker 10 inches away instead of going in a pocket.',
    why: 'Trains exact object-ball speed.',
    difficulty: 'Hard',
    category: 'novelty',
    table: 'A flat paper or coin marker on the cloth (coins only if the house allows)',
    setup: [
      '1-ball: 2.4 diamonds from the foot rail, 1.6 diamonds from the left long rail.',
      'Marker: 10 inches from the 1, on the line from the 1 to the foot-left corner.',
      'Cue ball: one diamond from the 1, straight behind it on the same line.',
    ],
    objectBall: '1-ball',
    pocket: 'None — the 1 must stop on the marker',
    tipZone: 'center',
    tipDetail: 'Stun center so the 1 dies on the marker.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather stun — measure distance carefully.',
    bridge: 'Quiet open bridge.',
    steps: [
      'Align centers through the marker.',
      'Feather center stun into the 1.',
      'The 1 should stop on the marker.',
    ],
    tips: ['Stopping on a marker trains pace better than pots alone.'],
    commonMistakes: ['Overhit — the 1 skates past the marker.'],
    successLooksLike: 'The 1 stops covering the marker.',
  },
  {
    id: 'sotd-48',
    name: 'Swing-Cut Showboat',
    tagline: 'Big outside cut that “swings” CB for shape',
    what: 'Cut the 1 55° into the foot-right corner and let the cue ball swing up the table.',
    why: 'Teaches big cut shots that move the cue ball a long way for position.',
    difficulty: 'Hard',
    category: 'position',
    table: 'Wide cut with a big CB swing',
    setup: [
      '1-ball: one diamond from the foot rail, one diamond from the right long rail.',
      'Cue ball: 1.7 diamonds from the 1, set for a 55° cut into the foot-right corner.',
      'After contact the CB swings off the right long rail up-table toward the head.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '3-right',
    tipDetail: 'Half a tip of right (outside) english; start with center, then add it.',
    english: 'Outside, half a tip, after center makes.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Medium pocket speed; let the cut create the swing.',
    bridge: 'Closed.',
    steps: [
      'Make the cut with center first (no swing pressure).',
      'Add outside english to widen CB swing for the camera.',
      'Stay down — the swing is post-contact theater.',
    ],
    tips: ['Exhibition is make % first, flair second.'],
    commonMistakes: ['Spin before you can pot the cut.'],
    successLooksLike: 'The 1 drops; the CB sweeps a wide, clean arc up-table.',
  },
  {
    id: 'sotd-49',
    name: 'Impossible-Looking Thin Cut',
    tagline: 'Artistic pool energy: cut that looks illegal',
    what: 'Make an edge-only 78° cut on a ball frozen to the rail so it rolls down the rail into the corner.',
    why: 'Builds trust in very thin contact and feather speed.',
    difficulty: 'Insane',
    category: 'position',
    table: 'Ultra-thin cut along the right long rail',
    setup: [
      '1-ball: frozen to the right long rail, 1.6 diamonds from the foot rail.',
      'Cue ball: on the foot string, 1.5 diamonds from the right long rail (5 inches toward the head from the 1).',
      '78° cut: an edge-only hit sends the 1 down the rail into the foot-right corner.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: 'center',
    tipDetail: 'Center tip; thin cuts + spin = chaos.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'feather',
    speedDetail: 'Feather. Anything firmer rattles or rails wrong.',
    bridge: 'Long, low, zen.',
    steps: [
      'See only a sliver of the OB.',
      'Breathe out; feather center stroke.',
      'Trust the micro-contact.',
    ],
    tips: ['If you can’t see a sliver, you’re aiming a miss — reset geometry.'],
    commonMistakes: ['Hit-and-hope power.'],
    successLooksLike: 'The 1 rolls down the right long rail and drops — crowd gasps optional.',
  },
  {
    id: 'sotd-50',
    name: 'Venom-Style Jump-Curve Tease',
    tagline: 'Hop the 7, then swerve right into the 1',
    what: 'Jump the cue ball over the 7, land, and let high-right spin curve it right into the 1, which drops in the foot-right corner.',
    why: 'A long-term challenge that combines jumping and swerving.',
    difficulty: 'Insane',
    category: 'jump',
    table: 'Jump over the 7, then a right swerve',
    setup: [
      '1-ball: 1.7 diamonds from the foot-right corner, 14 inches from the right long rail.',
      'Cue ball: one diamond from the right long rail, 1 inch past the center string.',
      '7-ball: 7.5 inches from the cue ball, on the jump line, blocking the direct path.',
      'The CB flies over the 7 on one direct line, lands 3.5 inches past it, then curves right over 20 inches into the 1.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-right corner',
    tipZone: '1:30-high-right',
    tipDetail: 'High-right, half a tip off each axis, with the jump cue at 50°.',
    english: 'Right side plus follow.',
    elevation: '50° with a jump cue; the elevation that makes it jump also makes it swerve after landing.',
    speed: 'firm',
    speedDetail: 'Firm dart; the swerve develops after landing.',
    bridge: 'Jump dart grip.',
    steps: [
      'Master the landing spot with a center-ball jump over the 7.',
      'Master the right swerve without the 7 on the table.',
      'Combine only when both work 7 times in 10.',
    ],
    tips: [
      'This is multi-month repertoire material — log sessions in Memories.',
      'Cloth safety > clout.',
    ],
    commonMistakes: ['Combining skills too early and scuffing cloth.'],
    successLooksLike: 'The CB hops the 7, lands, bends right, and pots the 1.',
  },
  {
    id: 'sotd-51',
    name: 'Massey Mirror Banks',
    tagline: 'Symmetric two-bank challenge — left then right',
    what: 'Bank the 1 from the head half into the left side pocket, then the 2 from the mirror spot in the foot half.',
    why: 'Shows whether your bank aim and speed work on both sides of the table.',
    difficulty: 'Hard',
    category: 'bank',
    table: 'Mirror bank pair across the center string',
    setup: [
      '1-ball: 4.2 inches from the right long rail, 1.8 diamonds from the right side pocket, in the head half.',
      '2-ball: the mirror spot in the foot half, 4.2 inches from the right long rail, 1.8 diamonds from the right side pocket.',
      'Cue ball: 1.4 diamonds from the 1.',
      'Route: 1-ball → right long rail → left side pocket.',
      'Make 3 from the head half, then mirror the same bank with the 2 from the foot half.',
    ],
    objectBall: '1-ball, then the 2-ball from the mirror spot',
    pocket: 'Left side pocket, banked off the right long rail (both balls)',
    tipZone: 'center',
    tipDetail: 'Center both sides — symmetry trains aim systems.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'Same speed both sides — that’s the point.',
    bridge: 'Match bridge both ways.',
    steps: [
      'Bank the 1 into the left side pocket with a called diamond and fixed speed.',
      'Mirror with the 2 from the foot half at the same speed.',
      'Only change aim, not stroke tempo.',
    ],
    tips: ['Exhibition consistency is bilateral — weak side exposes you.'],
    commonMistakes: ['Changing speed when the second side misses.'],
    successLooksLike: 'Both banks drop with the same stroke rhythm.',
  },
  {
    id: 'sotd-52',
    name: 'Rapid-Fire Spot Shots',
    tagline: 'Show pace: same pot, 10 times, no walk-around',
    what: 'Pot the 1 from the foot spot into the foot-left corner ten times from the same kitchen mark at one speed.',
    why: 'Builds consistency and a steady tempo under time pressure.',
    difficulty: 'Medium',
    category: 'novelty',
    table: '1-ball on the foot spot, cue ball in the kitchen',
    setup: [
      '1-ball: on the foot spot, replaced every rep.',
      'Cue ball: in the kitchen, 1.4 diamonds from the head rail, 10 inches from the right long rail; 31° cut into the foot-left corner.',
      'Goal: 8 in 10 in under two minutes.',
    ],
    objectBall: '1-ball',
    pocket: 'Foot-left corner — stick with it',
    tipZone: 'center',
    tipDetail: 'Center only — speedrun accuracy.',
    english: 'None.',
    elevation: 'Level.',
    speed: 'medium',
    speedDetail: 'One pre-chosen medium speed for all 10.',
    bridge: 'Your fastest stable routine.',
    steps: [
      'Mark CB and OB with chalk dots off-cloth references.',
      'Fire 10 strokes with full routine shortened but not skipped.',
      'Count makes; reset tomorrow if under 8.',
    ],
    tips: ['Exhibition polish is tempo under control, not rushed mess.'],
    commonMistakes: ['Skipping chalk and miscueing for “speed.”'],
    successLooksLike: '8+ pots, same corner, same pace — highlight ready.',
  },
];

export function catalogLength(): number {
  return SHOT_CATALOG.length;
}

export function getShotById(id: string): CatalogShot | undefined {
  return SHOT_CATALOG.find((s) => s.id === id);
}

export function getShotByIndex(index: number): CatalogShot {
  const i = ((index % SHOT_CATALOG.length) + SHOT_CATALOG.length) % SHOT_CATALOG.length;
  return SHOT_CATALOG[i];
}